// sshterm web module: clipboard — 复制粘贴 / safeSendInput
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;

// ---------- 复制粘贴 (Xshell 习惯, 防剪贴板竞争卡死) ----------
const COPY_MAX = 512 * 1024;   // 单次复制上限 512KB
let _lastCopyAt = 0;
let _clipBusy = false;         // 剪贴板操作互斥锁: 一次只允许一个, 防并发竞争死锁

function copySelection(term) {
  const sel = term.getSelection();
  if (!sel || _clipBusy) return false;
  _clipBusy = true;
  const toCopy = sel.length > COPY_MAX ? sel.slice(0, COPY_MAX) : sel;
  // 失败/超时静默处理: 不弹提示不重试 (系统剪贴板被其他程序锁定时快速放弃)
  const timer = setTimeout(() => { _clipBusy = false; }, 800);
  navigator.clipboard.writeText(toCopy).then(
    () => { clearTimeout(timer); _clipBusy = false; },
    () => { clearTimeout(timer); _clipBusy = false; });
  return true;
}
function pasteClipboard(term) {
  if (_clipBusy) return;
  _clipBusy = true;
  const timer = setTimeout(() => {
    _clipBusy = false;
    setStatus('剪贴板读取超时, 可用 Ctrl+Shift+V 粘贴');
  }, 1500);
  navigator.clipboard.readText().then(
    (t) => { clearTimeout(timer); _clipBusy = false; if (t) term.paste(t); },
    () => { clearTimeout(timer); _clipBusy = false; setStatus('剪贴板读取被拒, 可用 Ctrl+Shift+V 粘贴'); });
}
function safeSendInput(id, data) {
  // xterm delivers a pasted block as one data event; require confirmation for
  // blocks containing more than one line before anything reaches a server.
  const lines = String(data).split(/[\r\n]/).filter(Boolean).length;
  if (lines > 1 && !confirm(`即将粘贴 ${lines} 行内容到远程会话。确认发送？`)) {
    setStatus('已取消多行粘贴'); return;
  }
  sendInput(id, data);
}
function bindClipboard(tab) {
  const { term, host } = tab;

  // 1. 鼠标左键选中文本 → 自动复制
  // 点击风暴防护: ①clearTimeout 合并定时器 ②1 秒内点击超阈值进入防风暴模式, 完全停用复制
  let _stormCount = 0;
  let _stormUntil = 0;
  const inStorm = () => Date.now() < _stormUntil;
  const markClick = () => {
    const now = Date.now();
    if (now > _stormUntil) {
      _stormCount = (now - _stormUntil > 1000) ? 1 : _stormCount + 1;
      if (_stormCount > 12) {           // 1 秒内超过 12 次 = 风暴
        _stormUntil = now + 3000;       // 防风暴 3 秒: 完全不碰选择/剪贴板
        _stormCount = 0;
      }
    }
    return inStorm();
  };
  host.addEventListener('mouseup', (e) => {
    if (e.button !== 0) return;
    if (markClick()) return;            // 风暴中: 直接忽略, 不产生任何定时器
    clearTimeout(tab._copyTimer);
    tab._copyTimer = setTimeout(() => {
      try {
        const sel = term.getSelection();
        if (sel) copySelection(term);
      } catch (err) { /* 忽略 */ }
    }, 300);
  });

  // 2. 右键: 有选中文本 → 复制; 无选中 → 粘贴 (Xshell 习惯)
  host.addEventListener('contextmenu', (e) => {
    e.preventDefault();
    if (inStorm()) return;
    try { if (term.textarea) term.textarea.value = ''; } catch (err) { /* 忽略 */ }
    if (term.getSelection()) {
      copySelection(term);
      term.clearSelection();
    } else {
      pasteClipboard(term);
    }
  });

  // 3. 快捷键 (Ctrl/⌘ + C/V, Ctrl+Shift+C/V)
  term.attachCustomKeyEventHandler((e) => {
    if (e.type !== 'keydown') return true;
    const mod = e.ctrlKey || e.metaKey;
    const k = e.key.toLowerCase();
    if (mod && !e.shiftKey && k === 'r') {
      const session = owningSessionTab(tab);
      if (session && handleReconnectHotkey(session)) {
        e.preventDefault();
        return false;
      }
    }
    if (mod && !e.shiftKey && k === 'c') {
      if (term.getSelection()) { copySelection(term); return false; }
      return true;
    }
    // Ctrl+V / Shift+Ctrl+V: 不拦截, 交给 xterm.js 原生粘贴 (可靠且不耦合剪贴板权限)
    if (mod && e.shiftKey && k === 'c') { copySelection(term); return false; }
    if (mod && k === 'f') { openSearch(); return false; }
    return true;
  });
}

Sshterm.copySelection = typeof copySelection === 'function' ? copySelection : Sshterm.copySelection;
Sshterm.pasteClipboard = typeof pasteClipboard === 'function' ? pasteClipboard : Sshterm.pasteClipboard;
Sshterm.safeSendInput = typeof safeSendInput === 'function' ? safeSendInput : Sshterm.safeSendInput;
Sshterm.bindClipboard = typeof bindClipboard === 'function' ? bindClipboard : Sshterm.bindClipboard;
