// sshterm web module: host-cpu — 远端主机状态条 / CPU sparkline
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;

// ---------- 远端主机状态条 (仅 SSH 会话) ----------
function fmtDuration(ms) {
  if (!ms || ms < 0) return '0s';
  const s = Math.floor(ms / 1000);
  const d = Math.floor(s / 86400);
  const h = Math.floor((s % 86400) / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  if (d > 0) return `${d}天${h}时${m}分`;
  if (h > 0) return `${h}时${m}分${sec}秒`;
  if (m > 0) return `${m}分${sec}秒`;
  return `${sec}秒`;
}
const CPU_SPARK_N = 64;
const CPU_SPARK_W = 96;
const CPU_SPARK_H = 16;
const CPU_SPARK_FILL = '#3ecf8e';
const CPU_SPARK_STROKE = '#7eecc0';

function cpuSampleValue(hist, i, n) {
  const raw = hist[hist.length - n + i];
  const val = raw == null ? 0 : Number(raw);
  return Number.isFinite(val) ? Math.max(0, Math.min(100, val)) : 0;
}

function cpuSparkPoints(hist) {
  const w = CPU_SPARK_W, h = CPU_SPARK_H, n = CPU_SPARK_N;
  const pts = [];
  for (let i = 0; i < n; i++) {
    const val = cpuSampleValue(hist, i, n);
    pts.push({
      x: n <= 1 ? 0 : (i / (n - 1)) * w,
      y: 0.5 + (1 - val / 100) * (h - 1),
    });
  }
  return pts;
}

function cpuCatmullPath(pts) {
  if (!pts.length) return '';
  const h = CPU_SPARK_H;
  const clampY = (y) => Math.max(0, Math.min(h, y));
  let d = `M ${pts[0].x.toFixed(2)} ${pts[0].y.toFixed(2)}`;
  for (let i = 0; i < pts.length - 1; i++) {
    const p0 = pts[i - 1] || pts[i];
    const p1 = pts[i];
    const p2 = pts[i + 1];
    const p3 = pts[i + 2] || p2;
    const c1x = p1.x + (p2.x - p0.x) / 6;
    const c1y = clampY(p1.y + (p2.y - p0.y) / 6);
    const c2x = p2.x - (p3.x - p1.x) / 6;
    const c2y = clampY(p2.y - (p3.y - p1.y) / 6);
    d += ` C ${c1x.toFixed(2)} ${c1y.toFixed(2)} ${c2x.toFixed(2)} ${c2y.toFixed(2)} ${p2.x.toFixed(2)} ${p2.y.toFixed(2)}`;
  }
  return d;
}

function cpuSparkSvg(hist) {
  const w = CPU_SPARK_W, h = CPU_SPARK_H;
  const pts = cpuSparkPoints(hist || []);
  if (!pts.length) {
    return `<svg class="hi-spark" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" aria-hidden="true"></svg>`;
  }
  const top = cpuCatmullPath(pts);
  const rest = top.replace(/^M [-\d.]+ [-\d.]+/, '').trim();
  const area = `M 0 ${h} L ${pts[0].x.toFixed(2)} ${pts[0].y.toFixed(2)}${rest ? ` ${rest}` : ''} L ${w} ${h} Z`;
  return `<svg class="hi-spark" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" aria-hidden="true">` +
    `<path d="${area}" fill="${CPU_SPARK_FILL}" fill-opacity="0.92"/>` +
    `<path d="${top}" fill="none" stroke="${CPU_SPARK_STROKE}" stroke-width="1.1" stroke-linejoin="round" stroke-linecap="round"/>` +
    `</svg>`;
}

function pushCpuSample(tab, pct) {
  if (!Array.isArray(tab.cpuHist)) tab.cpuHist = [];
  if (!Array.isArray(tab.cpuDraw)) tab.cpuDraw = tab.cpuHist.slice();
  const v = Math.max(0, Math.min(100, Number(pct)));
  if (!Number.isFinite(v)) return;
  tab.cpuHist.push(v);
  if (tab.cpuHist.length > CPU_SPARK_N) tab.cpuHist.splice(0, tab.cpuHist.length - CPU_SPARK_N);
  const prev = tab.cpuDraw.length ? tab.cpuDraw[tab.cpuDraw.length - 1] : v;
  tab.cpuDraw.push(prev);
  if (tab.cpuDraw.length > CPU_SPARK_N) tab.cpuDraw.splice(0, tab.cpuDraw.length - CPU_SPARK_N);
}

function cpuPctClass(pct) {
  return pct >= 85 ? 'hi-warn' : (pct >= 60 ? 'hi-caution' : 'hi-ok');
}

function paintCpuWidget(tab, hist) {
  const wrap = tab.hostinfoBar && tab.hostinfoBar.querySelector('.hi-spark-wrap');
  if (!wrap) return;
  const pct = hist.length ? hist[hist.length - 1] : 0;
  const label = wrap.querySelector('[data-cpu-pct]');
  if (label) {
    label.className = cpuPctClass(pct);
    label.textContent = `${Math.round(pct)}%`;
  }
  const next = cpuSparkSvg(hist);
  const svg = wrap.querySelector('.hi-spark');
  if (svg) svg.outerHTML = next;
  else wrap.insertAdjacentHTML('beforeend', next);
}

function startCpuAnim(tab) {
  if (tab._cpuRaf) return;
  const step = () => {
    tab._cpuRaf = 0;
    const hist = tab.cpuHist || [];
    if (!Array.isArray(tab.cpuDraw)) tab.cpuDraw = hist.slice();
    while (tab.cpuDraw.length < hist.length) tab.cpuDraw.push(hist[tab.cpuDraw.length] ?? 0);
    let dirty = false;
    const len = Math.min(tab.cpuDraw.length, hist.length);
    for (let i = 0; i < len; i++) {
      const target = hist[i] ?? 0;
      const cur = tab.cpuDraw[i] ?? target;
      const next = cur + (target - cur) * 0.28;
      tab.cpuDraw[i] = next;
      if (Math.abs(target - next) > 0.2) dirty = true;
    }
    paintCpuWidget(tab, tab.cpuDraw);
    if (dirty) tab._cpuRaf = requestAnimationFrame(step);
  };
  tab._cpuRaf = requestAnimationFrame(step);
}

function stopCpuAnim(tab) {
  if (tab._cpuRaf) { cancelAnimationFrame(tab._cpuRaf); tab._cpuRaf = 0; }
}

function renderHostInfo(tab, s) {
  const bar = tab.hostinfoBar;
  if (!bar) return;
  if (s.error) {
    bar.innerHTML = `<span class="hi-item hi-muted">状态采集不可用</span>`;
    return;
  }
  const memPct = s.memPct != null ? s.memPct : 0;
  const memCls = memPct >= 85 ? 'hi-warn' : (memPct >= 60 ? 'hi-caution' : 'hi-ok');
  const dur = tab.connectedAt ? fmtDuration(Date.now() - tab.connectedAt) : '—';
  const cpuHist = tab.cpuDraw && tab.cpuDraw.length ? tab.cpuDraw : (tab.cpuHist || []);
  const cpuPct = cpuHist.length ? cpuHist[cpuHist.length - 1] : 0;
  const cpuCls = cpuPctClass(cpuPct);
  const ip = tab.cfg.host || '';
  const name = s.hostname || '';
  let html =
    `<span class="hi-item"><b>🖥 ${esc(name || ip)}</b> <span class="hi-muted">${esc(ip)}</span></span>` +
    `<span class="hi-item">💾 RAM <span class="${memCls}">${memPct}%</span> <span class="hi-muted">${fmtSize(s.memUsed)}/${fmtSize(s.memTotal)}</span></span>` +
    `<span class="hi-item">⚡ 负载 <span class="${memCls}">${s.load1}</span> <span class="hi-muted">(${s.load5}/${s.load15}, ${s.cores}核)</span></span>` +
    `<span class="hi-item hi-spark-wrap">💻 <span data-cpu-pct class="${cpuCls}">${Math.round(cpuPct)}%</span> ${cpuSparkSvg(cpuHist)}</span>` +
    `<span class="hi-item">⏱ 连接 <span class="hi-ok">${dur}</span></span>`;
  // 磁盘/挂载: 列出主要挂载点及用量 (按用量降序, 已取前 5)
  if (Array.isArray(s.disk) && s.disk.length) {
    const disks = s.disk.map(d => {
      const cls = d.pct >= 85 ? 'hi-warn' : (d.pct >= 60 ? 'hi-caution' : 'hi-ok');
      const mp = d.mp === '/' ? '根/' : d.mp;
      return `<span class="hi-disk"><span class="hi-muted">${esc(mp)}</span> <span class="${cls}">${d.pct}%</span> <span class="hi-muted">${fmtSize(d.total - d.avail)}/${fmtSize(d.total)}</span></span>`;
    }).join('');
    html += `<span class="hi-item hi-disks">💽 磁盘 ${disks}</span>`;
  }
  bar.innerHTML = html;
}
function startHostInfo(tab) {
  if (tab.hostinfoTimer) clearInterval(tab.hostinfoTimer);
  if (tab.cpuTimer) clearInterval(tab.cpuTimer);
  stopCpuAnim(tab);
  tab.connectedAt = Date.now();
  tab.cpuHist = [];
  tab.cpuDraw = [];
  const tick = () => send({ type: 'hostinfo', id: tab.id });
  const tickCpu = () => send({ type: 'hostcpu', id: tab.id });
  tick();
  tickCpu();
  tab.hostinfoTimer = setInterval(tick, 8000);
  tab.cpuTimer = setInterval(tickCpu, 400);
}


Sshterm.fmtDuration = typeof fmtDuration === 'function' ? fmtDuration : Sshterm.fmtDuration;
Sshterm.cpuSampleValue = typeof cpuSampleValue === 'function' ? cpuSampleValue : Sshterm.cpuSampleValue;
Sshterm.cpuSparkPoints = typeof cpuSparkPoints === 'function' ? cpuSparkPoints : Sshterm.cpuSparkPoints;
Sshterm.cpuCatmullPath = typeof cpuCatmullPath === 'function' ? cpuCatmullPath : Sshterm.cpuCatmullPath;
Sshterm.cpuSparkSvg = typeof cpuSparkSvg === 'function' ? cpuSparkSvg : Sshterm.cpuSparkSvg;
Sshterm.pushCpuSample = typeof pushCpuSample === 'function' ? pushCpuSample : Sshterm.pushCpuSample;
Sshterm.cpuPctClass = typeof cpuPctClass === 'function' ? cpuPctClass : Sshterm.cpuPctClass;
Sshterm.paintCpuWidget = typeof paintCpuWidget === 'function' ? paintCpuWidget : Sshterm.paintCpuWidget;
Sshterm.startCpuAnim = typeof startCpuAnim === 'function' ? startCpuAnim : Sshterm.startCpuAnim;
Sshterm.stopCpuAnim = typeof stopCpuAnim === 'function' ? stopCpuAnim : Sshterm.stopCpuAnim;
Sshterm.renderHostInfo = typeof renderHostInfo === 'function' ? renderHostInfo : Sshterm.renderHostInfo;
Sshterm.startHostInfo = typeof startHostInfo === 'function' ? startHostInfo : Sshterm.startHostInfo;
