// sshterm web module: hotkeys — 可配置快捷键映射
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;

var HOTKEY_STORAGE_KEY = 'sshterm.hotkeys';

var DEFAULT_HOTKEYS = {
  newConnection: { ctrl: true, shift: false, alt: false, key: 'n', labelZh: '新建连接', labelEn: 'New connection' },
  openSettings: { ctrl: true, shift: false, alt: false, key: ',', labelZh: '打开设置', labelEn: 'Open settings' },
  terminalSearch: { ctrl: true, shift: false, alt: false, key: 'f', labelZh: '终端搜索', labelEn: 'Terminal search' },
  manualReconnect: { ctrl: true, shift: false, alt: false, key: 'r', labelZh: '手动重连', labelEn: 'Manual reconnect' },
  fontIncrease: { ctrl: true, shift: false, alt: false, key: '=', labelZh: '增大字号', labelEn: 'Increase font' },
  fontDecrease: { ctrl: true, shift: false, alt: false, key: '-', labelZh: '减小字号', labelEn: 'Decrease font' },
  nextTab: { ctrl: true, shift: false, alt: false, key: 'tab', labelZh: '下一标签', labelEn: 'Next tab' },
  prevTab: { ctrl: true, shift: true, alt: false, key: 'tab', labelZh: '上一标签', labelEn: 'Previous tab' },
};

function cloneHotkey(entry) {
  return { ctrl: !!entry.ctrl, shift: !!entry.shift, alt: !!entry.alt, key: String(entry.key || '').toLowerCase(),
    labelZh: entry.labelZh, labelEn: entry.labelEn };
}

function loadHotkeys() {
  let stored = null;
  try { stored = JSON.parse(localStorage.getItem(HOTKEY_STORAGE_KEY) || 'null'); } catch {}
  const map = {};
  for (const [action, def] of Object.entries(DEFAULT_HOTKEYS)) {
    const override = stored && stored[action];
    map[action] = cloneHotkey(Object.assign({}, def, override || {}));
    map[action].labelZh = def.labelZh;
    map[action].labelEn = def.labelEn;
  }
  return map;
}

function saveHotkeys(map) {
  const out = {};
  for (const [action, entry] of Object.entries(map || {})) {
    out[action] = { ctrl: !!entry.ctrl, shift: !!entry.shift, alt: !!entry.alt, key: String(entry.key || '').toLowerCase() };
  }
  localStorage.setItem(HOTKEY_STORAGE_KEY, JSON.stringify(out));
}

function formatHotkey(entry) {
  if (!entry || !entry.key) return '';
  const parts = [];
  if (entry.ctrl) parts.push('Ctrl');
  if (entry.alt) parts.push('Alt');
  if (entry.shift) parts.push('Shift');
  const key = entry.key === ' ' ? 'Space' : entry.key.length === 1 ? entry.key.toUpperCase() : entry.key;
  parts.push(key === 'tab' ? 'Tab' : key);
  return parts.join('+');
}

function eventMatchesHotkey(e, entry) {
  if (!entry || !entry.key) return false;
  const mod = !!(e.ctrlKey || e.metaKey);
  if (!!entry.ctrl !== mod) return false;
  if (!!entry.shift !== !!e.shiftKey) return false;
  if (!!entry.alt !== !!e.altKey) return false;
  const k = String(e.key || '').toLowerCase();
  const want = String(entry.key).toLowerCase();
  if (want === '=' || want === '+') return k === '=' || k === '+';
  return k === want;
}

function isTypingTarget(el) {
  const tag = (el && el.tagName || '').toLowerCase();
  return tag === 'input' || tag === 'textarea' || tag === 'select' || !!(el && el.isContentEditable);
}

function getHotkeyAction(e, map) {
  const keys = map || loadHotkeys();
  for (const [action, entry] of Object.entries(keys)) {
    if (eventMatchesHotkey(e, entry)) return action;
  }
  return null;
}

function fillHotkeyEditor(root) {
  const el = root || $('hotkey-editor');
  if (!el) return;
  const map = loadHotkeys();
  const lang = (typeof LANG !== 'undefined' && LANG) || 'zh';
  el.innerHTML = '';
  for (const [action, entry] of Object.entries(map)) {
    const label = document.createElement('label');
    label.textContent = lang === 'en' ? (entry.labelEn || action) : (entry.labelZh || action);
    const input = document.createElement('input');
    input.type = 'text';
    input.readOnly = true;
    input.dataset.action = action;
    input.value = formatHotkey(entry);
    input.title = '点击后按下新快捷键';
    input.addEventListener('keydown', (ev) => {
      ev.preventDefault();
      ev.stopPropagation();
      if (ev.key === 'Escape') { input.blur(); return; }
      if (ev.key === 'Backspace' || ev.key === 'Delete') {
        // reset to default
        const def = DEFAULT_HOTKEYS[action];
        map[action] = cloneHotkey(def);
        input.value = formatHotkey(map[action]);
        saveHotkeys(map);
        return;
      }
      const key = String(ev.key || '').toLowerCase();
      if (key === 'control' || key === 'shift' || key === 'alt' || key === 'meta') return;
      map[action] = {
        ctrl: !!(ev.ctrlKey || ev.metaKey),
        shift: !!ev.shiftKey,
        alt: !!ev.altKey,
        key,
        labelZh: entry.labelZh,
        labelEn: entry.labelEn,
      };
      input.value = formatHotkey(map[action]);
      saveHotkeys(map);
    });
    el.appendChild(label);
    el.appendChild(input);
  }
}

Sshterm.DEFAULT_HOTKEYS = DEFAULT_HOTKEYS;
Sshterm.loadHotkeys = loadHotkeys;
Sshterm.saveHotkeys = saveHotkeys;
Sshterm.formatHotkey = formatHotkey;
Sshterm.eventMatchesHotkey = eventMatchesHotkey;
Sshterm.getHotkeyAction = getHotkeyAction;
Sshterm.fillHotkeyEditor = fillHotkeyEditor;
Sshterm.isTypingTarget = isTypingTarget;
