// sshterm web module: i18n — 中/英国际化
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;

// ---------- 国际化 (中/英) ----------
var I18N = {
  zh: {
    btn_new: '＋ 新建连接', btn_log: '📋 日志',
    btn_sftp: '📁 文件', btn_killall: '⏹ 全部关闭', btn_lang: '🌐 EN', btn_split: '⊞ 分屏',
    dl_title_new: '新建连接', dl_title_edit: '编辑会话',
    dl_conn: '连接', dl_save_conn: '保存并连接', dl_cancel: '取消',
    f_name: '会话名称', f_type: '类型', f_host: '主机', f_port: '端口',
    f_user: '用户名', f_auth: '认证方式', f_password: '密码', f_key: '私钥路径',
    f_passphrase: '密钥口令', f_proxy: '代理', f_proxy_addr: '代理地址',
    t_autologin: '自动登录', s_baud: '波特率', s_hex: 'HEX 显示/发送',
    sftp_up: '上级', sftp_upload: '上传', sftp_upload_dir: '传文件夹',
    sftp_refresh: '刷新', sftp_close: '关闭', sftp_dl: '下载', sftp_dir_dl: '下载目录',
    sftp_local_dir: '📂 本地目录', sftp_download_dir: '⬇ 下载当前目录',
    sftp_multi: '☑ 多选', sftp_multi_exit: '✕ 退出多选', sftp_select_all: '全选',
    sftp_download_sel: '⬇ 下载选中',
    sftp_op_rename: '重命名', sftp_op_delete: '删除', sftp_op_chmod: '权限',
    sftp_rename_prompt: '新名称:', sftp_rename_invalid: '名称无效(不能包含 /)',
    sftp_rename_done: '已重命名',
    sftp_delete_confirm: '确认删除该文件?',
    sftp_delete_dir_confirm: '确认递归删除该目录及其全部内容?',
    sftp_delete_done: '已删除',
    sftp_chmod_prompt: '权限 (八进制, 如 644):', sftp_chmod_invalid: '权限格式无效(3-4 位八进制)',
    sftp_chmod_file_only: '权限修改仅支持文件', sftp_chmod_done: '权限已修改',
    sftp_op_failed: '操作失败',
    mfa_jump: '跳板机', mfa_hint: '请输入验证码或多因素认证信息',
    side_title: '已保存会话', side_batch: '批量', side_foot: '双击连接 · 悬停可编辑/删除',
    session_filter: '过滤会话…', hotkeys_title: '快捷键',
    batch_all: '全选', batch_del: '删除选中', batch_cancel: '取消',
    close_title: '关闭会话?', close_ok: '确认关闭', welcome_p: 'SSH · Telnet · VNC · 串口 一体化连接工具',
    ws_ok: '服务器已连接', ws_off: '服务器已断开', ws_init: '未连接服务器',
  },
  en: {
    btn_new: '＋ New', btn_log: '📋 Log',
    btn_sftp: '📁 Files', btn_killall: '⏹ Close All', btn_lang: '🌐 中文', btn_split: '⊞ Split',
    dl_title_new: 'New Connection', dl_title_edit: 'Edit Session',
    dl_conn: 'Connect', dl_save_conn: 'Save & Connect', dl_cancel: 'Cancel',
    f_name: 'Name', f_type: 'Type', f_host: 'Host', f_port: 'Port',
    f_user: 'Username', f_auth: 'Auth', f_password: 'Password', f_key: 'Private Key',
    f_passphrase: 'Passphrase', f_proxy: 'Proxy', f_proxy_addr: 'Proxy Address',
    t_autologin: 'Auto login', s_baud: 'Baud', s_hex: 'HEX mode',
    sftp_up: 'Up', sftp_upload: 'Upload', sftp_upload_dir: 'Folder',
    sftp_refresh: 'Refresh', sftp_close: 'Close', sftp_dl: 'Download', sftp_dir_dl: 'Download folder',
    sftp_local_dir: '📂 Local folder', sftp_download_dir: '⬇ Download here',
    sftp_multi: '☑ Multi', sftp_multi_exit: '✕ Exit multi', sftp_select_all: 'All',
    sftp_download_sel: '⬇ Download selected',
    sftp_op_rename: 'Rename', sftp_op_delete: 'Delete', sftp_op_chmod: 'Chmod',
    sftp_rename_prompt: 'New name:', sftp_rename_invalid: 'Invalid name (must not contain /)',
    sftp_rename_done: 'Renamed',
    sftp_delete_confirm: 'Delete this file?',
    sftp_delete_dir_confirm: 'Recursively delete this directory and all its contents?',
    sftp_delete_done: 'Deleted',
    sftp_chmod_prompt: 'Mode (octal, e.g. 644):', sftp_chmod_invalid: 'Invalid mode (3-4 octal digits)',
    sftp_chmod_file_only: 'Chmod only supports files', sftp_chmod_done: 'Mode changed',
    sftp_op_failed: 'Operation failed',
    mfa_jump: 'Jump host', mfa_hint: 'Enter the verification code or multi-factor credential',
    side_title: 'Saved Sessions', side_batch: 'Batch', side_foot: 'Double-click to connect · hover to edit/delete',
    session_filter: 'Filter sessions…', hotkeys_title: 'Hotkeys',
    batch_all: 'All', batch_del: 'Delete', batch_cancel: 'Cancel',
    close_title: 'Close session?', close_ok: 'Close', welcome_p: 'SSH · Telnet · VNC · Serial all-in-one',
    ws_ok: 'Server connected', ws_off: 'Server disconnected', ws_init: 'Not connected',
  },
};

// Translate the complete static UI, including dialogs that are initially
// hidden. WeakMaps retain the original Chinese key so language switching is
// reversible, while the observer also covers controls rendered later.
const DOM_TEXT_EN = {
  '快捷键': 'Hotkeys',
  '自定义常用快捷键 (保存在本机 localStorage)。点击输入框后按下新组合键。': 'Customize common shortcuts (saved in localStorage). Click a field and press a new combo.',
  '点击后按下新快捷键': 'Click then press a new shortcut',
  'sshterm — SSH / Telnet / VNC / 串口': 'sshterm — SSH / Telnet / VNC / Serial',
  '＋ 新建连接': '＋ New Connection', '💾 保存会话': '💾 Save Session', '📁 文件': '📁 Files',
  '🔗 隧道': '🔗 Tunnels', '⏹ 全部关闭': '⏹ Close All', '☰ 工具': '☰ Tools',
  '📋 操作日志': '📋 Operation Log', '🌐 切换语言': '🌐 Language', '⏱ 定时发送': '⏱ Timed Send',
  '🔍 端口扫描': '🔍 Port Scan', '⇄ 导入 / 导出会话': '⇄ Import / Export Sessions',
  '⏺ 开始原始抓包': '⏺ Start Raw Capture', '⏺ 开始会话录制': '⏺ Start Recording',
  '▶ 导入并回放录制': '▶ Import & Replay Recording', '⊞ 分屏': '⊞ Split',
  '▣ 工作区': '▣ Workspace', '⚡ 命令': '⚡ Commands', '已保存会话': 'Saved Sessions',
  '默认': 'Default',
  '☑ 批量': '☑ Batch', '🔑 SSH 配置': '🔑 SSH Config', '全选': 'Select All',
  '删除选中': 'Delete Selected', '取消': 'Cancel', '双击连接 · 悬停可编辑/删除': 'Double-click to connect · hover to edit/delete',
  '双击编辑配置 · 或单击编辑按钮': 'Double-click to edit · or use the edit button',
  '就绪': 'Ready', '未连接服务器': 'Server disconnected', '服务器已连接': 'Server connected',
  '服务器已断开': 'Server disconnected', '连接中…': 'Connecting…', '● 已连接': '● Connected',
  '已连接': 'Connected', '已恢复原连接': 'Original Connection Restored',
  '✕ 已断开': '✕ Disconnected', '已断开': 'Disconnected', '出错': 'Error',
  '本地待传文件': 'Local Files', '远端目录': 'Remote Directory',
  '📂 本地目录': '📂 Local Folder', '⬇ 下载当前目录': '⬇ Download Folder',
  '未选择（下载前需指定）': 'Not selected (pick a folder before download)',
  '本地目录:': 'Local folder:',
  '下载失败': 'Download Failed',
  '已选': 'Selected', '项 · 目录将递归下载全部文件': ' · folders download all files recursively',
  '☑ 多选': '☑ Multi-select', '✕ 退出多选': '✕ Exit multi-select', '全选': 'Select all',
  '⬇ 下载选中': '⬇ Download selected',
  '⬆️传': '⬆ Upload', '📂传': '📂 Upload Folder', '⏸ 暂停队列': '⏸ Pause Queue',
  'SSH · Telnet · VNC · 串口 一体化连接工具': 'SSH · Telnet · VNC · Serial all-in-one',
  '新建连接': 'New Connection', '编辑会话': 'Edit Session', '会话名称': 'Session Name',
  '分组': 'Group', '类型': 'Type', '主机': 'Host', '端口': 'Port', '用户名': 'Username',
  '认证方式': 'Authentication', '密码': 'Password', '密钥': 'Key', '私钥路径': 'Private Key Path',
  '密钥口令': 'Key Passphrase', '代理': 'Proxy', '代理地址': 'Proxy Address', '代理认证': 'Proxy Authentication',
  '跳板链 (ProxyJump)': 'ProxyJump Chain', '跳板凭据（整条跳板链共用，独立于目标主机）': 'Jump Credentials (shared by the chain)',
  '跳板用户': 'Jump User', '跳板认证': 'Jump Authentication', '跳板密码': 'Jump Password',
  '跳板私钥路径': 'Jump Private Key Path', '跳板密钥口令': 'Jump Key Passphrase',
  '自动登录': 'Auto Login', '只读模式': 'View Only', '断线自动重连': 'Reconnect Automatically',
  '记住凭据（使用 Windows DPAPI 加密）': 'Remember Credentials (Windows DPAPI encrypted)',
  '记录会话日志（明文保存到本地文件，含终端输出）': 'Record Session Log (plain text saved locally, includes terminal output)',
  '连接后自动执行(每行一条)': 'Run After Connect (one command per line)', '串口': 'Serial',
  '波特率': 'Baud Rate', '数据位': 'Data Bits', '停止位': 'Stop Bits', '校验位': 'Parity',
  '编码': 'Encoding', 'RTS/CTS 硬件流控': 'RTS/CTS Hardware Flow Control',
  'HEX 显示/发送': 'HEX Display/Send', '接收显示时间戳': 'Show Receive Timestamps',
  '触发关键字': 'Trigger Keyword', '发送 Break': 'Send Break', '连接': 'Connect',
  '保存并连接': 'Save & Connect', '— 常用路径 —': '— Common Paths —', '无代理': 'No Proxy',
  '键盘交互/MFA': 'Keyboard Interactive / MFA', 'SSH Agent（含 FIDO2）': 'SSH Agent (including FIDO2)',
  'GBK (嵌入式常见)': 'GBK (common on embedded devices)',
  'SSH 配置 (SSH config)': 'SSH Config', '发现以下 Host 条目 (点击填充表单):': 'Host entries found (click to fill the form):',
  '关闭': 'Close', '⚠️ 关闭会话?': '⚠️ Close Session?', '确认关闭': 'Confirm Close',
  '⚡ 快捷命令': '⚡ Quick Commands', '命令名称': 'Command Name', '命令内容': 'Command',
  '连接后自动执行此命令集': 'Run This Command Set After Connect', '保存命令': 'Save Command',
  '执行全部': 'Run All', '🔌 串口被占用': '🔌 Serial Port In Use', '⏳ 等待重试': '⏳ Wait and Retry',
  '⚡ 强制释放': '⚡ Force Release', '等待重试: 占用方释放后自动连接;强制释放: 重启该串口设备(需管理员确认 UAC),其他程序将断开':
    'Wait and retry after the owner releases the port; force release restarts the device and requires UAC confirmation.',
  '目标': 'Target', '扫描': 'Scan', '单 IP → 全端口扫描;网段(含 / 或 -) → 网络扫描, 发现整个子网设备':
    'Single IP → full port scan; subnet (/ or -) → discover devices across the subnet.',
  '🔗 SSH 隧道': '🔗 SSH Tunnels', '为当前 SSH 会话创建端口转发/跳板隧道': 'Create port forwarding for the current SSH session.',
  '本地监听端口': 'Local Listen Port', '远端目标': 'Remote Target', '新建隧道': 'Add Tunnel', '刷新': 'Refresh',
  '本地转发 Local (本地端口 → 远端:端口)': 'Local Forward (local port → remote host:port)',
  '远端转发 Remote (远端端口 → 本地:端口)': 'Remote Forward (remote port → local host:port)',
  '动态转发 Dynamic (SOCKS5 代理)': 'Dynamic Forward (SOCKS5 Proxy)',
  '单会话最多 8 条隧道;端口冲突时会提示失败': 'Up to 8 tunnels per session; port conflicts are reported.',
  '发送内容': 'Content', '周期(毫秒)': 'Interval (ms)', '按 HEX 发送': 'Send as HEX', '立即开始': 'Start Immediately',
  '开始': 'Start', '停止': 'Stop', '▣ 默认工作区': '▣ Default Workspace',
  '保存或恢复当前打开的会话标签、标签顺序以及分屏布局。恢复时会关闭当前连接并重新建立已保存的会话。':
    'Save or restore open tabs, tab order, and split layout. Restoring reconnects the saved sessions.',
  '尚未保存工作区': 'No Workspace Saved', '保存当前工作区': 'Save Current Workspace',
  '恢复已保存工作区': 'Restore Saved Workspace',
  '工作区不会把密码或私钥保存到浏览器；未记住凭据的会话恢复后可能需要重新认证。':
    'Workspace data never stores passwords or private keys in the browser; authentication may be required after restore.',
  '★ 仅看书签': '★ Bookmarks Only', '🔐 仅看审计': '🔐 Audit Only', '⬇ 导出 CSV': '⬇ Export CSV',
  '日志文件: 加载中…': 'Log file: loading…', '每次启动工具自动新建日志文件, 关闭后保留在本地':
    'A new local log file is created on each start and retained after closing.',
  '导出 sshterm 加密备份': 'Export Encrypted sshterm Backup',
  '备份以 AES-256-GCM 加密，可跨设备导入；口令无法找回。': 'Backups use AES-256-GCM and can be imported on another device; passphrases cannot be recovered.',
  '备份口令': 'Backup Passphrase', '确认口令': 'Confirm Passphrase', '⬇ 导出加密备份': '⬇ Export Encrypted Backup',
  '导入 sshterm 加密备份': 'Import Encrypted sshterm Backup', '⬆ 导入备份': '⬆ Import Backup',
  '导入 OpenSSH config': 'Import OpenSSH Config',
  '导入具体 Host；通配符、Match 和 Include 规则会跳过。不会导入密码。':
    'Imports concrete Host entries; wildcard, Match, and Include rules are skipped. Passwords are never imported.',
  '⬆ 导入 OpenSSH config': '⬆ Import OpenSSH Config',
  '直接连接目标 VNC 服务，不依赖 SSH/终端会话；连接后会打开独立标签页。':
    'Connect directly to the target VNC service in a standalone tab.',
  'VNC 主机': 'VNC Host', '(加载中…)': '(Loading…)',
  '点击命令=立即发送到当前会话;连接后自动执行见"新建连接→SSH/Telnet→连接后执行"':
    'Click a command to send it; configure automatic execution in the connection dialog.',
  'SSH 多因素认证': 'SSH Multi-Factor Authentication',
  '提交': 'Submit',
  '⚙ 设置': '⚙ Settings',
  '终端外观设置': 'Terminal Appearance',
  '字体、主题与滚动回退保存在本机浏览器 (localStorage)，对新旧终端立即生效。':
    'Font, theme, and scrollback are saved in this browser (localStorage) and apply to new and existing terminals.',
  '配色主题': 'Color Theme',
  '字体家族': 'Font Family',
  '字号 (px)': 'Font Size (px)',
  '滚动回退行数': 'Scrollback Lines',
  '光标闪烁': 'Cursor Blink',
  '应用': 'Apply',
  '恢复默认': 'Reset Defaults',
};

const DOM_ATTR_EN = {
  '过滤会话…': 'Filter sessions…',
  '终端外观设置 (字体/主题/滚动)': 'Terminal appearance (font / theme / scrollback)',
  '新建连接 (Ctrl+N)': 'New Connection (Ctrl+N)', '保存当前会话配置': 'Save Current Session',
  'SSH 文件浏览/下载 (SFTP)': 'Browse/Download Files (SFTP)', 'SSH 隧道管理': 'SSH Tunnel Management',
  '断开并关闭全部会话标签': 'Disconnect and Close All Tabs', '更多工具': 'More Tools',
  '分屏(每次增加一格，最多 2×2 / 4 格；单格用 ✕ 关闭)': 'Split (add pane up to 2×2 / 4; close with ✕)', '保存或恢复当前标签与分屏布局': 'Save or Restore Tabs and Split Layout',
  '快捷命令(保存/执行/脚本)': 'Quick Commands', 'IP[:端口] 回车快速连接': 'IP[:port] — Enter to connect',
  '服务器连接状态': 'Server Connection Status', '批量管理': 'Batch Management', '解析 SSH config': 'Parse SSH Config',
  '拖动调整已保存会话宽度': 'Drag to Resize Saved Sessions',
  '搜索 (Enter=下一个, Shift+Enter=上一个, Esc=关闭)': 'Search (Enter=next, Shift+Enter=previous, Esc=close)',
  '上一个': 'Previous', '下一个': 'Next', '关闭': 'Close', '上级目录': 'Parent Directory',
  '当前目录': 'Current Directory', '上传文件到当前目录': 'Upload Files Here',
  '上传整个文件夹(含子目录)': 'Upload Folder Recursively', '刷新': 'Refresh',
  '选择下载保存的本地目录': 'Choose local folder for downloads',
  '将当前远端目录下载到本地目录': 'Download current remote folder to local directory',
  '多选文件/目录后批量下载': 'Multi-select files/folders for batch download',
  '全选当前目录': 'Select all in current folder',
  '下载选中项(目录递归展开)': 'Download selected (recursive for folders)',
  '关闭面板': 'Close Panel',
  '取消当前下载': 'Cancel Current Download', '拖动调整本地与远端目录宽度': 'Drag to Resize Local and Remote Columns',
  '如: 开发板串口': 'e.g. Board Serial', '如: 开发板 / 服务器': 'e.g. Boards / Servers',
  '密码': 'Password', '可选': 'Optional', '或手动输入私钥路径': 'Or Enter a Private Key Path',
  '用户名': 'Username', '留空则使用跳板链中的用户或目标用户': 'Leave blank to use the jump-chain or target username',
  '刷新串口列表': 'Refresh Serial Ports', '匹配后通知，不执行命令': 'Notify on match; do not execute commands',
  'VNC 密码': 'VNC Password', '如: 查看内核日志': 'e.g. View Kernel Log', '如: dmesg | tail -50': 'e.g. dmesg | tail -50',
  '按顺序执行全部命令': 'Run All Commands in Order', '要定时发送的内容': 'Content to Send',
  '至少 12 个字符': 'At Least 12 Characters',
  '192.168.1.216 或 192.168.1.0/24 或 192.168.1.1-254': '192.168.1.216 or 192.168.1.0/24 or 192.168.1.1-254',
  '如:\nls\ndmesg | tail -20': 'e.g.\nls\ndmesg | tail -20',
  '关闭此分屏': 'Close This Pane', '删除': 'Delete', '编辑': 'Edit', '拖动排序': 'Drag to Reorder',
  '文件面板仅 SSH 已连接时可用': 'Files are available only for a connected SSH session',
  '已连接': 'Connected', '已恢复原连接': 'Original Connection Restored',
  '连接中…': 'Connecting…', '已断开': 'Disconnected', '出错': 'Error',
};

const i18nTextKeys = new WeakMap();
const i18nAttrKeys = new WeakMap();

function translateDom(root = document) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    const current = node.nodeValue || '';
    const trimmed = current.trim();
    if (!trimmed) continue;
    let key = i18nTextKeys.get(node);
    if (!key || (trimmed !== key && trimmed !== DOM_TEXT_EN[key] && DOM_TEXT_EN[trimmed])) {
      if (DOM_TEXT_EN[trimmed]) { key = trimmed; i18nTextKeys.set(node, key); }
    }
    if (!key) continue;
    const value = LANG === 'en' ? DOM_TEXT_EN[key] : key;
    const leading = current.match(/^\s*/)?.[0] || '';
    const trailing = current.match(/\s*$/)?.[0] || '';
    const next = `${leading}${value}${trailing}`;
    if (node.nodeValue !== next) node.nodeValue = next;
  }
  const scope = root.querySelectorAll ? root : document;
  const elements = [];
  if (root.nodeType === Node.ELEMENT_NODE) elements.push(root);
  elements.push(...scope.querySelectorAll('[title],[placeholder]'));
  for (const el of elements) {
    let keys = i18nAttrKeys.get(el);
    if (!keys) { keys = {}; i18nAttrKeys.set(el, keys); }
    for (const attr of ['title', 'placeholder']) {
      const current = el.getAttribute?.(attr);
      if (!current) continue;
      let key = keys[attr];
      if (!key || (current !== key && current !== DOM_ATTR_EN[key] && DOM_ATTR_EN[current])) {
        if (DOM_ATTR_EN[current]) { key = current; keys[attr] = key; }
      }
      if (!key) continue;
      const value = LANG === 'en' ? DOM_ATTR_EN[key] : key;
      if (current !== value) el.setAttribute(attr, value);
    }
  }
}

let domTranslationObserver = null;
function installDomTranslationObserver() {
  if (domTranslationObserver || !document.body) return;
  domTranslationObserver = new MutationObserver(records => {
    for (const record of records) {
      if (record.type === 'characterData') translateDom(record.target.parentElement || document);
      else if (record.type === 'attributes') translateDom(record.target);
      else for (const node of record.addedNodes) {
        if (node.nodeType === Node.ELEMENT_NODE) translateDom(node);
        else if (node.parentElement) translateDom(node.parentElement);
      }
    }
  });
  domTranslationObserver.observe(document.body, {
    childList: true, subtree: true, characterData: true,
    attributes: true, attributeFilter: ['title', 'placeholder'],
  });
}
var LANG = localStorage.getItem('sshterm.lang') || 'zh';
function t(key) { return (I18N[LANG] && I18N[LANG][key]) || I18N.zh[key] || key; }
function applyI18n() {
  const map = {
    'btn-new': 'btn_new',
    'btn-sftp': 'btn_sftp', 'btn-killall': 'btn_killall', 'btn-split': 'btn_split',
    'side-title': 'side_title', 'btn-batch': 'side_batch', 'side-foot': 'side_foot',
  };
  const filterEl = document.getElementById('session-filter');
  if (filterEl) filterEl.placeholder = t('session_filter');
  for (const [id, key] of Object.entries(map)) {
    const el = document.getElementById(id);
    if (el) el.textContent = t(key);
  }
  const dyn = {
    'btn-dlg-conn': 'dl_conn', 'btn-dlg-save': 'dl_save_conn', 'btn-dlg-cancel': 'dl_cancel',
    'btn-close-ok': 'close_ok', 'btn-close-cancel': 'dl_cancel',
    'sftp-up': 'sftp_up', 'sftp-upload': 'sftp_upload', 'sftp-upload-dir': 'sftp_upload_dir',
    'sftp-refresh': 'sftp_refresh', 'sftp-close': 'sftp_close',
    'sftp-pick-download-dir': 'sftp_local_dir', 'sftp-download-current-dir': 'sftp_download_dir',
    'sftp-toggle-select': 'sftp_multi', 'sftp-select-all': 'sftp_select_all',
    'sftp-download-selected': 'sftp_download_sel',
    'batch-del-text': 'batch_del', 'batch-cancel': 'batch_cancel',
  };
  for (const [id, key] of Object.entries(dyn)) {
    const el = document.getElementById(id);
    if (el) el.textContent = t(key);
  }
  $('batch-all').parentElement.firstChild.textContent = t('batch_all') + ' ';
  $('dlg-title').textContent = t('dl_title_new');
  document.querySelectorAll('label[for]').forEach(() => {});
  document.documentElement.lang = LANG === 'en' ? 'en' : 'zh-CN';
  translateDom(document);
  installDomTranslationObserver();
  // 状态栏
  if (ws && ws.readyState === 1) $('conn-status-text').textContent = t('ws_ok');
}
function toggleLang() {
  LANG = LANG === 'zh' ? 'en' : 'zh';
  localStorage.setItem('sshterm.lang', LANG);
  applyI18n();
  setStatus(t(LANG === 'zh' ? 'ws_ok' : 'ws_ok'));
}

Sshterm.translateDom = typeof translateDom === 'function' ? translateDom : Sshterm.translateDom;
Sshterm.installDomTranslationObserver = typeof installDomTranslationObserver === 'function' ? installDomTranslationObserver : Sshterm.installDomTranslationObserver;
Sshterm.t = typeof t === 'function' ? t : Sshterm.t;
Sshterm.applyI18n = typeof applyI18n === 'function' ? applyI18n : Sshterm.applyI18n;
Sshterm.toggleLang = typeof toggleLang === 'function' ? toggleLang : Sshterm.toggleLang;
