// sshterm web module: i18n — 中/英国际化
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;

// ---------- 国际化 (中/英) ----------
var I18N = {
  zh: {
    btn_new: '新建', btn_local: '本地', btn_log: '日志',
    btn_sftp: '文件', btn_killall: '全部关闭', btn_lang: 'EN', btn_split: '分屏',
    btn_broadcast: '同步输入', btn_pane_max: '铺满',
    dl_title_new: '新建连接', dl_title_edit: '编辑会话',
    dl_conn: '连接', dl_save_conn: '保存并连接', dl_cancel: '取消',
    f_name: '会话名称', f_type: '类型', f_host: '主机', f_port: '端口',
    f_user: '用户名', f_auth: '认证方式', f_password: '密码', f_key: '私钥路径',
    f_passphrase: '密钥口令', f_proxy: '代理', f_proxy_addr: '代理地址',
    t_autologin: '自动登录', s_baud: '波特率', s_hex: 'HEX 显示/发送',
    sftp_up: '上一级', sftp_upload: '上传', sftp_upload_dir: '传文件夹',
    sftp_refresh: '刷新', sftp_close: '关闭', sftp_dl: '下载', sftp_dir_dl: '下载目录',
    sftp_local_dir: '本地目录', sftp_download_dir: '下载当前目录',
    sftp_multi: '多选', sftp_multi_exit: '退出多选', sftp_select_all: '全选',
    sftp_download_sel: '下载选中',
    sftp_op_rename: '重命名', sftp_op_delete: '删除', sftp_op_chmod: '权限',
    sftp_rename_prompt: '新名称:', sftp_rename_invalid: '名称无效(不能包含 /)',
    sftp_rename_done: '已重命名',
    sftp_delete_confirm: '确认删除该文件?',
    sftp_delete_dir_confirm: '确认递归删除该目录及其全部内容?',
    sftp_delete_done: '已删除',
    sftp_chmod_prompt: '权限 (八进制, 如 644):', sftp_chmod_invalid: '权限格式无效(3-4 位八进制)',
    sftp_chmod_file_only: '权限修改仅支持文件', sftp_chmod_done: '权限已修改',
    sftp_op_failed: '操作失败',
    mfa_jump: '跳板机', mfa_hint: '请输入验证码或多因素认证信息',
    side_title: '会话', side_batch: '批量', side_foot: '双击连接 · 悬停可编辑/删除',
    session_filter: '过滤会话…', hotkeys_title: '快捷键',
    batch_all: '全选', batch_del: '删除选中', batch_cancel: '取消',
    close_title: '关闭会话?', close_ok: '确认关闭', welcome_p: 'SSH · Telnet · VNC · 串口',
    ws_ok: '服务器已连接', ws_off: '服务器已断开', ws_init: '未连接服务器',
  },
  en: {
    btn_new: 'New', btn_local: 'Local', btn_log: 'Log',
    btn_sftp: 'Files', btn_killall: 'Close All', btn_lang: '中文', btn_split: 'Split',
    btn_broadcast: 'Broadcast', btn_pane_max: 'Maximize',
    dl_title_new: 'New Connection', dl_title_edit: 'Edit Session',
    dl_conn: 'Connect', dl_save_conn: 'Save & Connect', dl_cancel: 'Cancel',
    f_name: 'Name', f_type: 'Type', f_host: 'Host', f_port: 'Port',
    f_user: 'Username', f_auth: 'Auth', f_password: 'Password', f_key: 'Private Key',
    f_passphrase: 'Passphrase', f_proxy: 'Proxy', f_proxy_addr: 'Proxy Address',
    t_autologin: 'Auto login', s_baud: 'Baud', s_hex: 'HEX mode',
    sftp_up: 'Up', sftp_upload: 'Upload', sftp_upload_dir: 'Folder',
    sftp_refresh: 'Refresh', sftp_close: 'Close', sftp_dl: 'Download', sftp_dir_dl: 'Download folder',
    sftp_local_dir: 'Local folder', sftp_download_dir: 'Download folder',
    sftp_multi: 'Multi', sftp_multi_exit: 'Exit multi', sftp_select_all: 'All',
    sftp_download_sel: 'Download selected',
    sftp_op_rename: 'Rename', sftp_op_delete: 'Delete', sftp_op_chmod: 'Chmod',
    sftp_rename_prompt: 'New name:', sftp_rename_invalid: 'Invalid name (must not contain /)',
    sftp_rename_done: 'Renamed',
    sftp_delete_confirm: 'Delete this file?',
    sftp_delete_dir_confirm: 'Recursively delete this directory and all its contents?',
    sftp_delete_done: 'Deleted',
    sftp_chmod_prompt: 'Mode (octal, e.g. 644):', sftp_chmod_invalid: 'Invalid mode (3-4 octal digits)',
    sftp_chmod_file_only: 'Chmod only supports files', sftp_chmod_done: 'Mode changed',
    sftp_op_failed: 'Operation failed',
    mfa_jump: 'Jump host', mfa_hint: 'Enter the verification code or multi-factor credential',
    side_title: 'Sessions', side_batch: 'Batch', side_foot: 'Double-click to connect · hover to edit/delete',
    session_filter: 'Filter sessions…', hotkeys_title: 'Hotkeys',
    batch_all: 'All', batch_del: 'Delete', batch_cancel: 'Cancel',
    close_title: 'Close session?', close_ok: 'Close', welcome_p: 'SSH · Telnet · VNC · Serial',
    ws_ok: 'Server connected', ws_off: 'Server disconnected', ws_init: 'Not connected',
  },
};

// Translate the complete static UI, including dialogs that are initially
// hidden. WeakMaps retain the original Chinese key so language switching is
// reversible, while the observer also covers controls rendered later.
const DOM_TEXT_EN = {
  '快捷键': 'Hotkeys',
  '自定义常用快捷键 (保存在本机 localStorage)。点击输入框后按下新组合键。': 'Customize common shortcuts (saved in localStorage). Click a field and press a new combo.',
  '点击后按下新快捷键': 'Click then press a new shortcut',
  'xterm — SSH / Telnet / VNC / 串口': 'xterm — SSH / Telnet / VNC / Serial',
  '新建': 'New', '本地': 'Local', '文件': 'Files', '隧道': 'Tunnels',
  '全部关闭': 'Close All', '工具': 'Tools',
  '操作日志': 'Operation Log', '切换语言': 'Language', '定时发送': 'Timed Send',
  '端口扫描': 'Port Scan', '导入 / 导出会话': 'Import / Export Sessions',
  '开始原始抓包': 'Start Raw Capture', '开始会话录制': 'Start Recording',
  '导入并回放录制': 'Import & Replay Recording', '分屏': 'Split', '铺满': 'Maximize',
  '放到左侧': 'Drop left', '放到右侧': 'Drop right', '放到上方': 'Drop above', '放到下方': 'Drop below',
  '完成': 'Done',
  '同步输入': 'Broadcast', '换行': 'Newline',
  '工作区': 'Workspace', '命令': 'Commands', '设置': 'Settings',
  '会话': 'Sessions', '已保存会话': 'Saved Sessions',
  '默认': 'Default',
  '批量': 'Batch', 'SSH 配置': 'SSH Config', '刷新': 'Refresh', '全选': 'Select All',
  '上一级': 'Up', '上传': 'Upload', '传文件夹': 'Upload Folder', '多选': 'Multi-select',
  '下载选中': 'Download selected', '本地目录': 'Local folder', '下载当前目录': 'Download folder',
  '关闭': 'Close', '暂停队列': 'Pause Queue',
  '删除选中': 'Delete Selected', '取消': 'Cancel', '双击连接 · 悬停可编辑/删除': 'Double-click to connect · hover to edit/delete',
  '双击编辑配置 · 或单击编辑按钮': 'Double-click to edit · or use the edit button',
  '就绪': 'Ready', '未连接服务器': 'Server disconnected', '服务器已连接': 'Server connected',
  '服务器已断开': 'Server disconnected', '连接中…': 'Connecting…', '● 已连接': '● Connected',
  '已连接': 'Connected', '已恢复原连接': 'Original Connection Restored',
  '✕ 已断开': '✕ Disconnected', '已断开': 'Disconnected', '出错': 'Error',
  '本地待传文件': 'Local Files', '远端目录': 'Remote Directory',
  '名称': 'Name', '大小': 'Size', '修改': 'Modified',
  '📂 本地目录': '📂 Local Folder', '⬇ 下载当前目录': '⬇ Download Folder',
  '未选择（下载前需指定）': 'Not selected (pick a folder before download)',
  '本地目录:': 'Local folder:',
  '下载失败': 'Download Failed',
  '已选': 'Selected', '项 · 目录将递归下载全部文件': '· folders download all files recursively',
  '☑ 多选': '☑ Multi-select', '✕ 退出多选': '✕ Exit multi-select', '全选': 'Select all',
  '⬇ 下载选中': '⬇ Download selected',
  '⬆️传': '⬆ Upload', '📂传': '📂 Upload Folder', '⏸ 暂停队列': '⏸ Pause Queue',
  'SSH · Telnet · VNC · 串口': 'SSH · Telnet · VNC · Serial',
  'SSH · Telnet · VNC · 串口 一体化连接工具': 'SSH · Telnet · VNC · Serial all-in-one',
  '新建连接': 'New Connection',
  '新建连接': 'New Connection', '编辑会话': 'Edit Session', '会话名称': 'Session Name',
  '分组': 'Group', '类型': 'Type', '主机': 'Host', '端口': 'Port', '用户名': 'Username',
  '认证方式': 'Authentication', '密码': 'Password', '密钥': 'Key', '私钥路径': 'Private Key Path',
  '密钥口令': 'Key Passphrase', '代理': 'Proxy', '代理地址': 'Proxy Address', '代理认证': 'Proxy Authentication',
  '跳板链 (ProxyJump)': 'ProxyJump Chain', '跳板凭据（整条跳板链共用，独立于目标主机）': 'Jump Credentials (shared by the chain)',
  '跳板用户': 'Jump User', '跳板认证': 'Jump Authentication', '跳板密码': 'Jump Password',
  '跳板私钥路径': 'Jump Private Key Path', '跳板密钥口令': 'Jump Key Passphrase',
  '自动登录': 'Auto Login', '只读模式': 'View Only', '断线自动重连': 'Reconnect Automatically',
  '记住凭据（使用 Windows DPAPI 加密）': 'Remember Credentials (Windows DPAPI encrypted)',
  '记录会话日志（明文保存到本地文件，含终端输出）': 'Record Session Log (plain text saved locally, includes terminal output)',
  '连接后自动执行(每行一条)': 'Run After Connect (one command per line)', '串口': 'Serial',
  '波特率': 'Baud Rate', '数据位': 'Data Bits', '停止位': 'Stop Bits', '校验位': 'Parity',
  '编码': 'Encoding', 'RTS/CTS 硬件流控': 'RTS/CTS Hardware Flow Control',
  'HEX 显示/发送': 'HEX Display/Send', '接收显示时间戳': 'Show Receive Timestamps',
  '工作目录': 'Working Directory', '进程退出后自动重开': 'Restart after the process exits',
  '没有检测到本机 Shell': 'No local shell detected',
  '在当前 Windows 用户权限下打开本机终端，不会把命令发到远程主机。':
    'Opens a local terminal as the current Windows user. Commands stay on this machine.',
  '触发关键字': 'Trigger Keyword', '发送 Break': 'Send Break', '连接': 'Connect',
  '保存并连接': 'Save & Connect', '— 常用路径 —': '— Common Paths —', '无代理': 'No Proxy',
  '键盘交互/MFA': 'Keyboard Interactive / MFA', 'SSH Agent（含 FIDO2）': 'SSH Agent (including FIDO2)',
  'GBK (嵌入式常见)': 'GBK (common on embedded devices)',
  'SSH 配置 (SSH config)': 'SSH Config', '发现以下 Host 条目 (点击填充表单):': 'Host entries found (click to fill the form):',
  '别名': 'Alias',
  '关闭': 'Close',   '关闭会话?': 'Close Session?', '⚠️ 关闭会话?': '⚠️ Close Session?', '确认关闭': 'Confirm Close',
  '快捷命令': 'Quick Commands', '⚡ 快捷命令': '⚡ Quick Commands', '命令名称': 'Command Name', '命令内容': 'Command',
  '连接后自动执行此命令集': 'Run This Command Set After Connect', '保存命令': 'Save Command',
  '执行全部': 'Run All', '串口被占用': 'Serial Port In Use', '🔌 串口被占用': '🔌 Serial Port In Use',
  '等待重试': 'Wait and Retry', '⏳ 等待重试': '⏳ Wait and Retry',
  '强制释放': 'Force Release', '⚡ 强制释放': '⚡ Force Release',
  '等待重试: 占用方释放后自动连接;强制释放: 重启该串口设备(需管理员确认 UAC),其他程序将断开':
    'Wait and retry after the owner releases the port; force release restarts the device and requires UAC confirmation.',
  '目标': 'Target', '扫描': 'Scan', '单 IP → 全端口扫描;网段(含 / 或 -) → 网络扫描, 发现整个子网设备':
    'Single IP → full port scan; subnet (/ or -) → discover devices across the subnet.',
  'SSH 隧道': 'SSH Tunnels', '🔗 SSH 隧道': '🔗 SSH Tunnels',
  '为当前 SSH 会话创建端口转发/跳板隧道': 'Create port forwarding for the current SSH session.',
  '当前会话': 'Current session',
  '已启用': 'Active', '新建转发': 'New Forward',
  '把本机端口转到 SSH 对面那台机器上的服务。例如本机 18080 → 远端 127.0.0.1:80，浏览器访问 http://127.0.0.1:18080 即可。':
    'Forward a local port to a service on the SSH host. Example: local 18080 → remote 127.0.0.1:80, then open http://127.0.0.1:18080.',
  '本地转发': 'Local Forward', '远端转发': 'Remote Forward', 'SOCKS5': 'SOCKS5',
  '本机监听端口': 'Local Listen Port', '本机目标端口': 'Local Target Port',
  '本机 SOCKS 端口': 'Local SOCKS Port',
  '远端目标': 'Remote Target', '远端目标 (主机:端口)': 'Remote Target (host:port)',
  '远端监听端口': 'Remote Listen Port',
  '本机访问：http://127.0.0.1:18080 → 远端 127.0.0.1:80': 'Local access: http://127.0.0.1:18080 → remote 127.0.0.1:80',
  '创建隧道': 'Create Tunnel', '新建隧道': 'Add Tunnel', '刷新': 'Refresh', '复制': 'Copy', '删除': 'Delete',
  '还没有隧道。': 'No tunnels yet.',
  '在右侧选一种转发方式后点「创建隧道」。': 'Pick a forward type on the right, then click Create Tunnel.',
  '加载中…': 'Loading…',
  '单会话最多 8 条；只监听 127.0.0.1，不对外网开放。端口已被占用时会提示失败。':
    'Up to 8 per session; listens on 127.0.0.1 only. Busy ports are reported as failures.',
  '单会话最多 8 条隧道;端口冲突时会提示失败': 'Up to 8 tunnels per session; port conflicts are reported.',
  '隧道类型': 'Tunnel type',
  '发送内容': 'Content', '周期(毫秒)': 'Interval (ms)', '按 HEX 发送': 'Send as HEX', '立即开始': 'Start Immediately',
  '开始': 'Start', '停止': 'Stop', '默认工作区': 'Default Workspace', '▣ 默认工作区': '▣ Default Workspace',
  '保存或恢复当前打开的会话标签、标签顺序以及分屏布局。恢复时会关闭当前连接并重新建立已保存的会话。':
    'Save or restore open tabs, tab order, and split layout. Restoring reconnects the saved sessions.',
  '尚未保存工作区': 'No Workspace Saved', '保存当前工作区': 'Save Current Workspace',
  '恢复已保存工作区': 'Restore Saved Workspace',
  '工作区不会把密码或私钥保存到浏览器；未记住凭据的会话恢复后可能需要重新认证。':
    'Workspace data never stores passwords or private keys in the browser; authentication may be required after restore.',
  '★ 仅看书签': '★ Bookmarks Only', '🔐 仅看审计': '🔐 Audit Only', '⬇ 导出 CSV': '⬇ Export CSV',
  '日志文件: 加载中…': 'Log file: loading…', '每次启动工具自动新建日志文件, 关闭后保留在本地':
    'A new local log file is created on each start and retained after closing.',
  '导出 sshterm 加密备份': 'Export Encrypted sshterm Backup',
  '备份以 AES-256-GCM 加密，可跨设备导入；口令无法找回。': 'Backups use AES-256-GCM and can be imported on another device; passphrases cannot be recovered.',
  '备份口令': 'Backup Passphrase', '确认口令': 'Confirm Passphrase', '⬇ 导出加密备份': '⬇ Export Encrypted Backup',
  '导入 sshterm 加密备份': 'Import Encrypted sshterm Backup', '⬆ 导入备份': '⬆ Import Backup',
  '导入 OpenSSH config': 'Import OpenSSH Config',
  '导入具体 Host；通配符、Match 和 Include 规则会跳过。不会导入密码。':
    'Imports concrete Host entries; wildcard, Match, and Include rules are skipped. Passwords are never imported.',
  '⬆ 导入 OpenSSH config': '⬆ Import OpenSSH Config',
  '直接连接目标 VNC 服务，不依赖 SSH/终端会话；连接后会打开独立标签页。':
    'Connect directly to the target VNC service in a standalone tab.',
  'VNC 主机': 'VNC Host', '(加载中…)': '(Loading…)',
  '点击命令=立即发送到当前会话;连接后自动执行见"新建连接→SSH/Telnet→连接后执行"':
    'Click a command to send it; configure automatic execution in the connection dialog.',
  'SSH 多因素认证': 'SSH Multi-Factor Authentication',
  '提交': 'Submit',
  '⚙ 设置': '⚙ Settings',
  '外观': 'Appearance',
  '这里改终端长什么样。点右下角「应用」后立刻作用到已打开的标签，并保存在这台电脑的浏览器里。':
    'Change how the terminal looks. Click Apply to update open tabs; settings stay in this browser.',
  '点右侧组合键框，再按下新的按键。改完马上生效，不用点「应用」。按 Delete 或「还原」恢复该项默认。':
    'Click a shortcut box, then press a new combo. Changes apply immediately. Delete or Reset restores the default.',
  '配色主题': 'Color Theme',
  '文字、背景和光标颜色。默认 Tokyo Night。': 'Text, background, and cursor colors. Default is Tokyo Night.',
  '字体': 'Font',
  '选常见等宽字体；选「自定义」可手填 CSS 字体列表。': 'Pick a common monospace font, or choose Custom to type a CSS font stack.',
  'Consolas（Windows 常见）': 'Consolas (common on Windows)',
  'Cascadia Mono': 'Cascadia Mono',
  'JetBrains Mono': 'JetBrains Mono',
  '更纱黑体等宽（中文更清晰）': 'Sarasa Mono (clearer CJK)',
  '微软雅黑 + Consolas': 'YaHei + Consolas',
  '自定义…': 'Custom…',
  '字号': 'Font Size',
  '终端文字大小，单位像素。也可在终端里用快捷键加减。': 'Terminal text size in pixels. You can also change it with shortcuts.',
  '回滚行数': 'Scrollback',
  '向上滚动能看到多少历史输出。越大越占内存，一般 5000～20000 即可。':
    'How many past lines you can scroll back. Larger uses more memory; 5000–20000 is typical.',
  '光标闪烁': 'Cursor Blink',
  '块状光标是否闪动，方便看清当前输入位置。': 'Blink the block cursor so the insert point is easier to see.',
  '启用闪烁': 'Enable blink',
  '功能': 'Action',
  '组合键': 'Shortcut',
  '还原': 'Reset',
  '行': 'lines',
  '应用': 'Apply',
  '恢复默认': 'Reset Defaults',
};

const DOM_ATTR_EN = {
  '过滤会话…': 'Filter sessions…',
  '终端外观设置 (字体/主题/滚动)': 'Settings (appearance / hotkeys)',
  '关闭': 'Close',
  '设置分类': 'Settings categories',
  '恢复这项默认快捷键': 'Restore this default shortcut',
  '点击后按下新快捷键': 'Click then press a new shortcut',
  '新建连接 (Ctrl+N)': 'New Connection (Ctrl+N)',
  '打开本机终端 (PowerShell / CMD / WSL / Git Bash)': 'Open a local terminal (PowerShell / CMD / WSL / Git Bash)',
  '保存当前会话配置': 'Save Current Session',
  'SSH 文件浏览/下载 (SFTP)': 'Browse/Download Files (SFTP)', 'SSH 隧道管理': 'SSH Tunnel Management',
  '复制访问地址': 'Copy access address', '删除': 'Delete', '关闭': 'Close',
  '断开并关闭全部会话标签': 'Disconnect and Close All Tabs', '更多工具': 'More Tools',
  '分屏(每次增加一格，最多 2×2 / 4 格；单格用 ✕ 关闭)': 'Split (add pane up to 2×2 / 4; close with ✕)',
  '临时铺满当前分屏，再按一次恢复': 'Temporarily maximize the focused pane; press again to restore',
  '放到左侧': 'Drop left', '放到右侧': 'Drop right', '放到上方': 'Drop above', '放到下方': 'Drop below',
  '完成': 'Done', '有新输出': 'New output', '输出已停': 'Output stopped',
  '把键盘输入同步到所有已连接的终端标签和分屏': 'Mirror keyboard input to every connected terminal tab and split pane',
  '保存或恢复当前标签与分屏布局': 'Save or Restore Tabs and Split Layout',
  '快捷命令(保存/执行/脚本)': 'Quick Commands', 'IP[:端口] 回车快速连接': 'IP[:port] — Enter to connect',
  '服务器连接状态': 'Server Connection Status', '批量管理': 'Batch Management', '解析 SSH config': 'Parse SSH Config',
  '拖动调整已保存会话宽度': 'Drag to Resize Saved Sessions',
  '搜索 (Enter=下一个, Shift+Enter=上一个, Esc=关闭)': 'Search (Enter=next, Shift+Enter=previous, Esc=close)',
  '上一个': 'Previous', '下一个': 'Next', '关闭': 'Close', '上级目录': 'Parent Directory',
  '当前目录': 'Current Directory', '上传文件到当前目录': 'Upload Files Here',
  '上传整个文件夹(含子目录)': 'Upload Folder Recursively', '刷新': 'Refresh',
  '选择下载保存的本地目录': 'Choose local folder for downloads',
  '将当前远端目录下载到本地目录': 'Download current remote folder to local directory',
  '多选文件/目录后批量下载': 'Multi-select files/folders for batch download',
  '全选当前目录': 'Select all in current folder',
  '下载选中项(目录递归展开)': 'Download selected (recursive for folders)',
  '关闭面板': 'Close Panel',
  '取消当前下载': 'Cancel Current Download', '拖动调整本地与远端目录宽度': 'Drag to Resize Local and Remote Columns',
  '如: 开发板串口': 'e.g. Board Serial', '如: 开发板 / 服务器': 'e.g. Boards / Servers',
  '密码': 'Password', '可选': 'Optional', '或手动输入私钥路径': 'Or Enter a Private Key Path',
  '用户名': 'Username', '留空则使用跳板链中的用户或目标用户': 'Leave blank to use the jump-chain or target username',
  '刷新串口列表': 'Refresh Serial Ports', '留空则使用用户主目录': 'Leave blank to use the user profile directory',
  '匹配后通知，不执行命令': 'Notify on match; do not execute commands',
  'VNC 密码': 'VNC Password', '如: 查看内核日志': 'e.g. View Kernel Log', '如: dmesg | tail -50': 'e.g. dmesg | tail -50',
  '按顺序执行全部命令': 'Run All Commands in Order', '要定时发送的内容': 'Content to Send',
  '至少 12 个字符': 'At Least 12 Characters',
  '192.168.1.216 或 192.168.1.0/24 或 192.168.1.1-254': '192.168.1.216 or 192.168.1.0/24 or 192.168.1.1-254',
  '如:\nls\ndmesg | tail -20': 'e.g.\nls\ndmesg | tail -20',
  '关闭此分屏': 'Close This Pane', '删除': 'Delete', '编辑': 'Edit', '拖动排序': 'Drag to Reorder',
  '文件面板仅 SSH 已连接时可用': 'Files are available only for a connected SSH session',
  '已连接': 'Connected', '已恢复原连接': 'Original Connection Restored',
  '连接中…': 'Connecting…', '已断开': 'Disconnected', '出错': 'Error',
};

const i18nTextKeys = new WeakMap();
const i18nAttrKeys = new WeakMap();

function i18nSkip(node) {
  if (!node || node.nodeType === Node.DOCUMENT_NODE || node.nodeType === Node.DOCUMENT_FRAGMENT_NODE) return false;
  const el = node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement;
  if (!el) return true;
  return !!el.closest('script, style, textarea, #terms, .xterm');
}

let i18nDepth = 0;
function translateDom(root = document) {
  if (!root || i18nSkip(root)) return;
  i18nDepth += 1;
  if (i18nDepth === 1 && domTranslationObserver) domTranslationObserver.disconnect();
  try {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        return i18nSkip(node) ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT;
      },
    });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    for (const node of nodes) {
      const current = node.nodeValue || '';
      const trimmed = current.trim();
      if (!trimmed) continue;
      let key = i18nTextKeys.get(node);
      if (!key || (trimmed !== key && trimmed !== DOM_TEXT_EN[key] && DOM_TEXT_EN[trimmed])) {
        if (DOM_TEXT_EN[trimmed]) { key = trimmed; i18nTextKeys.set(node, key); }
      }
      if (!key) continue;
      const value = String(LANG === 'en' ? DOM_TEXT_EN[key] : key).trim();
      const leading = current.match(/^\s*/)?.[0] || '';
      const trailing = current.match(/\s*$/)?.[0] || '';
      const next = `${leading}${value}${trailing}`;
      if (node.nodeValue !== next) node.nodeValue = next;
    }
    const scope = root.querySelectorAll ? root : document;
    const elements = [];
    if (root.nodeType === Node.ELEMENT_NODE && !i18nSkip(root)) elements.push(root);
    elements.push(...scope.querySelectorAll('[title],[placeholder]'));
    for (const el of elements) {
      if (i18nSkip(el)) continue;
      let keys = i18nAttrKeys.get(el);
      if (!keys) { keys = {}; i18nAttrKeys.set(el, keys); }
      for (const attr of ['title', 'placeholder']) {
        const current = el.getAttribute?.(attr);
        if (!current) continue;
        let key = keys[attr];
        if (!key || (current !== key && current !== DOM_ATTR_EN[key] && DOM_ATTR_EN[current])) {
          if (DOM_ATTR_EN[current]) { key = current; keys[attr] = key; }
        }
        if (!key) continue;
        const value = LANG === 'en' ? DOM_ATTR_EN[key] : key;
        if (current !== value) el.setAttribute(attr, value);
      }
    }
  } finally {
    i18nDepth -= 1;
    if (i18nDepth === 0 && domTranslationObserver && document.body) watchI18nDom();
  }
}

let domTranslationObserver = null;
function watchI18nDom() {
  domTranslationObserver.observe(document.body, {
    childList: true, subtree: true, characterData: true,
    attributes: true, attributeFilter: ['title', 'placeholder'],
  });
}
function installDomTranslationObserver() {
  if (domTranslationObserver || !document.body) return;
  domTranslationObserver = new MutationObserver(records => {
    if (i18nDepth > 0) return;
    for (const record of records) {
      if (record.type === 'characterData') {
        const parent = record.target.parentElement;
        if (parent) translateDom(parent);
      } else if (record.type === 'attributes') translateDom(record.target);
      else for (const node of record.addedNodes) {
        if (node.nodeType === Node.ELEMENT_NODE) translateDom(node);
        else if (node.parentElement) translateDom(node.parentElement);
      }
    }
  });
  watchI18nDom();
}
var LANG = localStorage.getItem('sshterm.lang') || 'zh';
function t(key) { return (I18N[LANG] && I18N[LANG][key]) || I18N.zh[key] || key; }
function applyI18n() {
  const map = {
    'btn-new': 'btn_new', 'btn-local': 'btn_local',
    'btn-sftp': 'btn_sftp', 'btn-killall': 'btn_killall', 'btn-split': 'btn_split',
    'btn-pane-max': 'btn_pane_max', 'btn-broadcast': 'btn_broadcast',
    'side-title': 'side_title', 'btn-batch': 'side_batch', 'side-foot': 'side_foot',
  };
  const filterEl = document.getElementById('session-filter');
  if (filterEl) filterEl.placeholder = t('session_filter');
  for (const [id, key] of Object.entries(map)) {
    const el = document.getElementById(id);
    if (el) el.textContent = t(key);
  }
  const dyn = {
    'btn-dlg-conn': 'dl_conn', 'btn-dlg-save': 'dl_save_conn', 'btn-dlg-cancel': 'dl_cancel',
    'btn-close-ok': 'close_ok', 'btn-close-cancel': 'dl_cancel',
    'sftp-up': 'sftp_up', 'sftp-upload': 'sftp_upload', 'sftp-upload-dir': 'sftp_upload_dir',
    'sftp-refresh': 'sftp_refresh', 'sftp-close': 'sftp_close',
    'sftp-pick-download-dir': 'sftp_local_dir', 'sftp-download-current-dir': 'sftp_download_dir',
    'sftp-toggle-select': 'sftp_multi', 'sftp-select-all': 'sftp_select_all',
    'sftp-download-selected': 'sftp_download_sel',
    'batch-del-text': 'batch_del', 'batch-cancel': 'batch_cancel',
  };
  for (const [id, key] of Object.entries(dyn)) {
    const el = document.getElementById(id);
    if (el) el.textContent = t(key);
  }
  $('batch-all').parentElement.firstChild.textContent = t('batch_all') + ' ';
  $('dlg-title').textContent = t('dl_title_new');
  document.querySelectorAll('label[for]').forEach(() => {});
  document.documentElement.lang = LANG === 'en' ? 'en' : 'zh-CN';
  translateDom(document);
  installDomTranslationObserver();
  // 状态栏
  if (ws && ws.readyState === 1) $('conn-status-text').textContent = t('ws_ok');
}
function toggleLang() {
  LANG = LANG === 'zh' ? 'en' : 'zh';
  localStorage.setItem('sshterm.lang', LANG);
  applyI18n();
  setStatus(t(LANG === 'zh' ? 'ws_ok' : 'ws_ok'));
}

Sshterm.translateDom = typeof translateDom === 'function' ? translateDom : Sshterm.translateDom;
Sshterm.installDomTranslationObserver = typeof installDomTranslationObserver === 'function' ? installDomTranslationObserver : Sshterm.installDomTranslationObserver;
Sshterm.t = typeof t === 'function' ? t : Sshterm.t;
Sshterm.applyI18n = typeof applyI18n === 'function' ? applyI18n : Sshterm.applyI18n;
Sshterm.toggleLang = typeof toggleLang === 'function' ? toggleLang : Sshterm.toggleLang;
