// sshterm web module: reconnect — 自动重连策略 / Ctrl+R
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;

function resetReconnectState(tab) {
  if (!tab) return;
  tab.reconnectAttempts = 0;
  tab.autoReconnectExhausted = false;
  tab.manualReconnectArmed = false;
}

function shouldQuietReconnectError(tab, m) {
  if (!tab || !m || m.action || tab.intentionalClose || !tab.everConnected) return false;
  return tab.cfg.reconnect !== false || !!tab.manualReconnectArmed || !!tab.autoReconnectExhausted;
}

function shouldCaptureReconnectHotkey(tab) {
  if (!tab || !tabs.includes(tab) || tab.intentionalClose || !tab.everConnected) return false;
  if (tab.state === 'connected') return false;
  return tab.cfg.reconnect !== false || !!tab.manualReconnectArmed || !!tab.autoReconnectExhausted;
}

function startSessionConnect(tab) {
  if (tab.cfg.type === 'vnc') connectVncTab(tab);
  else send({ type: 'connect', session: tab.cfg, id: tab.id });
}

function armManualReconnect(tab) {
  tab.autoReconnectExhausted = true;
  tab.manualReconnectArmed = true;
  setTabState(tab.id, 'closed', MANUAL_RECONNECT_HINT);
}

function handleReconnectHotkey(tab) {
  if (!shouldCaptureReconnectHotkey(tab)) return false;
  if (tab.state === 'connecting') return true;
  cancelReconnect(tab);
  tab.manualReconnectArmed = false;
  setTabState(tab.id, 'connecting', '正在重连…');
  startSessionConnect(tab);
  return true;
}

function cancelReconnect(tab) {
  if (tab && tab.reconnectTimer) {
    clearTimeout(tab.reconnectTimer);
    tab.reconnectTimer = null;
  }
}
function scheduleReconnect(tab, reason) {
  if (!tab || tab.intentionalClose || tab.cfg.reconnect === false || tab.reconnectTimer) return;
  if (tab.cfg.type === 'serial' && _occTab === tab) return;
  if (tab.autoReconnectExhausted) {
    armManualReconnect(tab);
    return;
  }
  tab.reconnectAttempts = (tab.reconnectAttempts || 0) + 1;
  if (tab.reconnectAttempts > AUTO_RECONNECT_MAX) {
    armManualReconnect(tab);
    return;
  }
  const delay = AUTO_RECONNECT_DELAYS[tab.reconnectAttempts - 1];
  setTabState(tab.id, 'connecting', `断线, ${delay / 1000} 秒后第 ${tab.reconnectAttempts} 次重连…`);
  tab.reconnectTimer = setTimeout(() => {
    tab.reconnectTimer = null;
    if (!tab.intentionalClose && tabs.includes(tab)) startSessionConnect(tab);
  }, delay);
}

let draggingTabId = null;

Sshterm.resetReconnectState = typeof resetReconnectState === 'function' ? resetReconnectState : Sshterm.resetReconnectState;
Sshterm.shouldQuietReconnectError = typeof shouldQuietReconnectError === 'function' ? shouldQuietReconnectError : Sshterm.shouldQuietReconnectError;
Sshterm.shouldCaptureReconnectHotkey = typeof shouldCaptureReconnectHotkey === 'function' ? shouldCaptureReconnectHotkey : Sshterm.shouldCaptureReconnectHotkey;
Sshterm.startSessionConnect = typeof startSessionConnect === 'function' ? startSessionConnect : Sshterm.startSessionConnect;
Sshterm.armManualReconnect = typeof armManualReconnect === 'function' ? armManualReconnect : Sshterm.armManualReconnect;
Sshterm.handleReconnectHotkey = typeof handleReconnectHotkey === 'function' ? handleReconnectHotkey : Sshterm.handleReconnectHotkey;
Sshterm.cancelReconnect = typeof cancelReconnect === 'function' ? cancelReconnect : Sshterm.cancelReconnect;
Sshterm.scheduleReconnect = typeof scheduleReconnect === 'function' ? scheduleReconnect : Sshterm.scheduleReconnect;
