// sshterm web module: sftp-panel — SFTP 面板 UI / 列表 / 工具栏
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;
// ---------- SFTP 文件面板 (SSH) ----------
let sftpOpen = false;
let sftpConnId = null;
let sftpDownloadDirHandle = null;
let sftpPendingScan = null;
let sftpSelectMode = false;
let sftpSelectedItems = new Map();
let sftpListEntries = [];

function renderSftpDownloadDirLabel() {
  const label = $('sftp-download-dir-label');
  if (!label) return;
  label.textContent = sftpDownloadDirHandle
    ? (sftpDownloadDirHandle.name || '已选择目录')
    : '未选择（下载前需指定）';
}

async function pickSftpDownloadDir() {
  if (!window.showDirectoryPicker) {
    setStatus('当前浏览器不支持选择本地目录，请使用 Chrome 或 Edge');
    return null;
  }
  try {
    sftpDownloadDirHandle = await window.showDirectoryPicker({ mode: 'readwrite' });
    renderSftpDownloadDirLabel();
    setStatus(`下载将保存到本地目录: ${sftpDownloadDirHandle.name}`);
    return sftpDownloadDirHandle;
  } catch (e) {
    if (e.name !== 'AbortError') setStatus(`选择目录失败: ${e.message}`);
    return null;
  }
}

async function ensureSftpDownloadDir() {
  if (sftpDownloadDirHandle) {
    try {
      const perm = await sftpDownloadDirHandle.queryPermission({ mode: 'readwrite' });
      if (perm === 'granted') return sftpDownloadDirHandle;
      if (perm !== 'denied') {
        const req = await sftpDownloadDirHandle.requestPermission({ mode: 'readwrite' });
        if (req === 'granted') return sftpDownloadDirHandle;
      }
    } catch {}
    sftpDownloadDirHandle = null;
    renderSftpDownloadDirLabel();
  }
  return pickSftpDownloadDir();
}

async function sftpLocalFileHandle(fileName) {
  const dir = await ensureSftpDownloadDir();
  if (!dir) return null;
  try {
    const created = await createLocalFile(dir, fileName);
    return created.handle;
  } catch (e) {
    throw new Error(`无法在本地目录创建 ${fileName}: ${e.message}`);
  }
}

const WIN_RESERVED = new Set([
  'con', 'prn', 'aux', 'nul',
  'com1', 'com2', 'com3', 'com4', 'com5', 'com6', 'com7', 'com8', 'com9',
  'lpt1', 'lpt2', 'lpt3', 'lpt4', 'lpt5', 'lpt6', 'lpt7', 'lpt8', 'lpt9',
]);

function sanitizeLocalPathSegment(name) {
  let s = String(name || '').replace(/\\/g, '/').split('/').pop() || '';
  try { s = s.normalize('NFKC'); } catch {}
  s = s.replace(/[\u0000-\u001f\u007f\u200b-\u200d\ufeff\ufffd]/g, '').trim();
  s = s.replace(/^[. ]+|[. ]+$/g, '');
  s = s.replace(/[<>:"|?*]/g, '_');
  if (!s || s === '.' || s === '..') return '';
  if (WIN_RESERVED.has(s.toLowerCase())) s = `_${s}`;
  return s.slice(0, 240);
}

async function localEntryIsDirectory(parent, name) {
  try {
    await parent.getDirectoryHandle(name);
    return true;
  } catch { return false; }
}

async function localEntryIsFile(parent, name) {
  try {
    await parent.getFileHandle(name);
    return true;
  } catch { return false; }
}

function buildLocalFileCandidates(base, stem, ext, preferAltFirst) {
  const out = [];
  const add = (n) => { if (n && !out.includes(n)) out.push(n); };
  if (!preferAltFirst) add(base);
  add(`${stem}_file${ext}`);
  for (let i = 1; i <= 30; i++) add(`${stem}_${i}${ext}`);
  if (ext) {
    add(`${stem}.download`);
    add(`${stem}.txt`);
  }
  add(`sshterm_${Date.now().toString(36)}${ext || '.bin'}`);
  return out;
}

function sanitizeLocalFileName(name) {
  return sanitizeLocalPathSegment(name);
}

function splitRelativePath(relativePath) {
  return String(relativePath || '')
    .replace(/\\/g, '/')
    .split('/')
    .map((p) => sanitizeLocalPathSegment(p))
    .filter(Boolean);
}

async function sftpGetOrCreateDir(parent, rawName) {
  const base = sanitizeLocalPathSegment(rawName);
  if (!base) throw new Error(`无效目录名: ${rawName}`);
  let lastError = '';
  for (let i = 0; i < 50; i++) {
    let candidate = i ? `${base}_${i}` : base;
    if (await localEntryIsFile(parent, candidate)) candidate = i ? `${base}_${i}_dir` : `${base}_dir`;
    try {
      return await parent.getDirectoryHandle(candidate);
    } catch (eOpen) {
      lastError = String(eOpen.message || eOpen) || lastError;
      try {
        return await parent.getDirectoryHandle(candidate, { create: true });
      } catch (e) {
        const msg = String(e.message || e);
        lastError = msg || lastError;
        if (/not allowed|already exists|TypeMismatch/i.test(msg)) continue;
        throw new Error(`无法创建目录 ${rawName} (${candidate}): ${msg}`);
      }
    }
  }
  throw new Error(`${lastError || '无法创建目录'}（已重试 50 次）`);
}

async function sftpEnsureLocalDir(rootDir, parts) {
  let cur = rootDir;
  for (const part of parts) {
    cur = await sftpGetOrCreateDir(cur, part);
  }
  return cur;
}

async function createLocalFile(parent, fileName) {
  const base = sanitizeLocalFileName(fileName);
  if (!base) throw new Error(`无效文件名: ${fileName}`);
  const dot = base.lastIndexOf('.');
  const stem = dot > 0 ? base.slice(0, dot) : base;
  const ext = dot > 0 ? base.slice(dot) : '';
  const canRetry = (msg) => /not allowed|already exists|TypeMismatch|access denied|拒绝访问|permission|denied/i.test(msg);
  const dirBlocksBase = await localEntryIsDirectory(parent, base);
  const candidates = buildLocalFileCandidates(base, stem, ext, dirBlocksBase);
  let lastError = '';
  let attempts = 0;

  for (const candidate of candidates) {
    attempts++;
    if (await localEntryIsDirectory(parent, candidate)) {
      lastError = `本地已有同名目录 ${candidate}`;
      continue;
    }
    try {
      const handle = await parent.getFileHandle(candidate, { create: true });
      return { handle, localName: candidate };
    } catch (e1) {
      const msg1 = String(e1.message || e1);
      lastError = msg1 || lastError;
      if (canRetry(msg1)) {
        try {
          const handle = await parent.getFileHandle(candidate);
          return { handle, localName: candidate };
        } catch (e2) {
          lastError = String(e2.message || e2) || lastError;
        }
        continue;
      }
      throw new Error(msg1);
    }
  }
  throw new Error(`${lastError || '无法写入本地文件'}（已重试 ${attempts} 次）`);
}

async function sftpLocalNestedFileHandle(rootDir, relativePath) {
  const parts = splitRelativePath(relativePath);
  if (!parts.length) throw new Error(`无效路径: ${relativePath}`);
  const fileName = parts.pop();
  let parent = rootDir;
  if (parts.length) {
    parent = await sftpEnsureLocalDir(rootDir, parts);
  }
  const created = await createLocalFile(parent, fileName);
  const prefix = parts.length ? `${parts.join('/')}/` : '';
  return { handle: created.handle, localName: prefix + created.localName };
}

function sftpRemoteBaseName(remotePath) {
  const p = String(remotePath || '').replace(/\/+$/, '');
  if (!p || p === '.') return 'download';
  const idx = p.lastIndexOf('/');
  return idx >= 0 ? p.slice(idx + 1) || 'download' : p;
}

function sftpScanRemoteDir(remotePath) {
  return new Promise((resolve, reject) => {
    if (sftpPendingScan) return reject(new Error('已有目录扫描进行中'));
    const timer = setTimeout(() => {
      if (sftpPendingScan) {
        sftpPendingScan = null;
        reject(new Error('扫描远端目录超时'));
      }
    }, 120000);
    sftpPendingScan = {
      id: sftpConnId,
      resolve: (m) => { clearTimeout(timer); resolve(m); },
      reject: (e) => { clearTimeout(timer); reject(e); },
    };
    send({ type: 'sftp', id: sftpConnId, action: 'scan', path: remotePath || sftpPath });
  });
}

async function downloadSftpCurrentDir() {
  if (!sftpConnId || !sftpPath) return setStatus('请先打开文件面板');
  if (activeDownload) return setStatus('已有下载进行中，请先完成或取消');
  const localRoot = await ensureSftpDownloadDir();
  if (!localRoot) return;
  await runSftpBatchDownload([{
    name: sftpRemoteBaseName(sftpPath),
    isDir: true,
    full: sftpPath,
  }], localRoot, '下载目录');
}

function updateSftpSelectUi() {
  const on = sftpSelectMode;
  $('sftp-toggle-select')?.classList.toggle('active', on);
  if ($('sftp-toggle-select')) $('sftp-toggle-select').textContent = on ? t('sftp_multi_exit') : t('sftp_multi');
  $('sftp-select-all')?.classList.toggle('hidden', !on);
  $('sftp-download-selected')?.classList.toggle('hidden', !on);
  $('sftp-select-bar')?.classList.toggle('hidden', !on);
  $('sftp-select-count') && ($('sftp-select-count').textContent = String(sftpSelectedItems.size));
}

function toggleSftpSelectMode() {
  sftpSelectMode = !sftpSelectMode;
  if (!sftpSelectMode) sftpSelectedItems.clear();
  updateSftpSelectUi();
  if (sftpListEntries.length) renderSftpList(sftpListEntries);
}

function toggleSftpSelection(full, entry) {
  if (sftpSelectedItems.has(full)) sftpSelectedItems.delete(full);
  else sftpSelectedItems.set(full, { name: entry.name, isDir: entry.isDir, full });
  updateSftpSelectUi();
  const row = [...($('sftp-list')?.querySelectorAll('.sftp-item') || [])].find((r) => r.dataset.full === full);
  row?.classList.toggle('selected', sftpSelectedItems.has(full));
  const cb = row?.querySelector('.sftp-select-cb');
  if (cb) cb.checked = sftpSelectedItems.has(full);
  if ($('sftp-status') && sftpListEntries.length) {
    $('sftp-status').textContent = `${sftpListEntries.length} 项 · 已选 ${sftpSelectedItems.size}`;
  }
}

function selectAllSftpEntries() {
  for (const e of sftpListEntries) {
    const full = sftpJoin(sftpPath, e.name);
    sftpSelectedItems.set(full, { name: e.name, isDir: e.isDir, full });
  }
  updateSftpSelectUi();
  renderSftpList(sftpListEntries);
}

function prepareMirrorFileList(scan) {
  const files = (scan.files || [])
    .filter((f) => f.name && splitRelativePath(f.name).length)
    .sort((a, b) => {
      const depth = (p) => (String(p.name).match(/\//g) || []).length;
      const d = depth(b) - depth(a);
      return d || String(a.name).localeCompare(String(b.name));
    });
  const skipped = (scan.skipped || 0) + ((scan.files || []).length - files.length);
  return { files, skipped };
}

function newDownloadCtx(task, controller) {
  return {
    task, controller, doneFiles: 0, totalFiles: 0, loadedBytes: 0, totalBytes: 0,
    skipped: 0, failedFiles: [], renamedFiles: [],
  };
}

async function downloadMirrorFiles(files, targetRoot, label, ctx) {
  ctx.totalFiles += files.length;
  ctx.totalBytes += files.reduce((s, f) => s + (f.size || 0), 0);
  for (const file of files) {
    if (ctx.controller.signal.aborted) throw Object.assign(new Error('aborted'), { name: 'AbortError' });
    const url = apiUrl('/api/sftp/download', { conn: sftpConnId, path: file.path });
    const fileStart = ctx.loadedBytes;
    try {
      const { handle, localName } = await sftpLocalNestedFileHandle(targetRoot, file.name);
      await streamDownloadToFile(url, Promise.resolve(handle), (loaded) => {
        const overall = fileStart + loaded;
        const pct = ctx.totalBytes > 0 ? Math.min(100, overall / ctx.totalBytes * 100) : undefined;
        const failText = ctx.failedFiles.length ? `，失败 ${ctx.failedFiles.length}` : '';
        const skippedText = ctx.skipped ? `，跳过 ${ctx.skipped}` : '';
        showProgress(
          `下载: ${label} ${ctx.doneFiles}/${ctx.totalFiles} 文件 (${fmtSize(overall)}/${fmtSize(ctx.totalBytes)}${failText}${skippedText})`,
          pct,
        );
        updateTransferTask(ctx.task, pct);
      }, 3, { controller: ctx.controller, manageActive: false });
      ctx.loadedBytes += file.size || 0;
      ctx.doneFiles++;
      const baseName = file.name.split('/').pop();
      const savedBase = localName.split('/').pop();
      if (savedBase !== baseName) ctx.renamedFiles.push({ name: file.name, localName });
    } catch (e) {
      if (e.name === 'AbortError') throw e;
      ctx.failedFiles.push({ name: `${label}/${file.name}`, error: e.message || String(e) });
    }
  }
}

async function downloadRemoteDirMirror(remotePath, localRoot, subfolderName, ctx) {
  showProgress(`扫描远端目录: ${remotePath}`, undefined);
  const scan = await sftpScanRemoteDir(remotePath);
  const { files, skipped } = prepareMirrorFileList(scan);
  ctx.skipped += skipped;
  if (!files.length) return;
  const targetRoot = await sftpGetOrCreateDir(localRoot, subfolderName);
  await downloadMirrorFiles(files, targetRoot, subfolderName, ctx);
}

async function downloadRemoteFileMirror(remotePath, localRoot, fileName, ctx) {
  ctx.totalFiles += 1;
  if (ctx.controller.signal.aborted) throw Object.assign(new Error('aborted'), { name: 'AbortError' });
  const url = apiUrl('/api/sftp/download', { conn: sftpConnId, path: remotePath });
  try {
    const { handle, localName } = await sftpLocalNestedFileHandle(localRoot, fileName);
    await streamDownloadToFile(url, Promise.resolve(handle), (loaded, total) => {
      ctx.loadedBytes += loaded;
      ctx.totalBytes += total || 0;
      showProgress(`下载: ${fileName} ${fmtSize(loaded)}`, undefined);
    }, 3, { controller: ctx.controller, manageActive: false });
    ctx.doneFiles++;
    if (localName.split('/').pop() !== fileName.split('/').pop()) {
      ctx.renamedFiles.push({ name: fileName, localName });
    }
  } catch (e) {
    if (e.name === 'AbortError') throw e;
    ctx.failedFiles.push({ name: fileName, error: e.message || String(e) });
  }
}

function finalizeDownloadCtx(ctx, label) {
  const { task, failedFiles, renamedFiles, doneFiles, totalFiles, skipped } = ctx;
  const skippedText = skipped ? `，远端跳过 ${skipped}` : '';
  if (failedFiles.length) {
    const failList = formatFailedFileSummary(failedFiles);
    const summary = `完成 ${doneFiles}/${totalFiles}，失败 ${failedFiles.length}${skippedText}`;
    renderSftpFailures(failedFiles);
    doneProgress(`⚠ 部分下载: ${label} (${summary})，失败: ${failList}`);
    updateTransferTask(task, 100, 'partial', summary, failedFiles);
    setStatus(`部分下载: 失败 ${failList}`);
    $('sftp-status').textContent = failedFiles.map((f) => `${f.name}: ${f.error}`).join('；');
  } else {
    renderSftpFailures([]);
    const renameText = renamedFiles.length ? `，${renamedFiles.length} 个已改名保存` : '';
    doneProgress(`✅ 已下载: ${label} (${totalFiles} 文件${skippedText}${renameText})`);
    updateTransferTask(task, 100, 'done', skipped ? `完成，跳过 ${skipped}` : '完成');
    setStatus(`下载完成: ${label} (${totalFiles} 文件${renameText})`);
    if (renamedFiles.length) {
      $('sftp-status').textContent = renamedFiles.map((f) => `${f.name} → ${f.localName}`).join('；');
    }
  }
}

async function runSftpBatchDownload(items, localRoot, taskKind) {
  const sorted = [...items].sort((a, b) => (b.isDir - a.isDir) || a.name.localeCompare(b.name));
  const label = sorted.length === 1 ? sorted[0].name : `${sorted.length} 项`;
  const task = newTransferTask(taskKind, label);
  renderSftpFailures([]);
  const controller = new AbortController();
  activeDownload = { controller };
  const cancel = $('sftp-cancel-transfer');
  cancel.classList.remove('hidden');
  cancel.onclick = cancelActiveDownload;
  const ctx = newDownloadCtx(task, controller);
  try {
    for (const item of sorted) {
      try {
        if (item.isDir) await downloadRemoteDirMirror(item.full, localRoot, item.name, ctx);
        else await downloadRemoteFileMirror(item.full, localRoot, item.name, ctx);
      } catch (e) {
        if (e.name === 'AbortError') throw e;
        ctx.failedFiles.push({ name: item.name, error: e.message || String(e) });
      }
    }
    if (!ctx.totalFiles) {
      $('sftp-progress').classList.add('hidden');
      updateTransferTask(task, undefined, 'done', ctx.skipped ? `空目录，跳过 ${ctx.skipped}` : '空目录');
      return setStatus('所选目录为空或无可下载文件');
    }
    finalizeDownloadCtx(ctx, label);
  } catch (err) {
    $('sftp-progress').classList.add('hidden');
    const cancelled = err && err.name === 'AbortError';
    const msg = cancelled ? '下载已取消' : (err.message || '失败');
    $('sftp-status').textContent = cancelled ? '下载已取消' : `下载失败: ${msg}`;
    updateTransferTask(task, undefined, cancelled ? 'cancelled' : 'failed', cancelled ? '已取消' : msg);
    if (!cancelled) setStatus(`下载失败: ${msg}`);
  } finally {
    activeDownload = null;
    cancel.classList.add('hidden');
    cancel.onclick = null;
  }
}

async function downloadSftpSelected() {
  if (!sftpConnId) return setStatus('请先打开文件面板');
  if (!sftpSelectedItems.size) return setStatus('请先勾选要下载的文件或目录');
  const localRoot = await ensureSftpDownloadDir();
  if (!localRoot) return;
  const items = [...sftpSelectedItems.values()];
  await runSftpBatchDownload(items, localRoot, '下载选中');
  sftpSelectMode = false;
  sftpSelectedItems.clear();
  updateSftpSelectUi();
  if (sftpListEntries.length) renderSftpList(sftpListEntries);
}

async function downloadSftpItem(entry, fullPath) {
  if (!sftpConnId) return setStatus('请先打开文件面板');
  const localRoot = await ensureSftpDownloadDir();
  if (!localRoot) return;
  await runSftpBatchDownload([{
    name: entry.name,
    isDir: !!entry.isDir,
    full: fullPath,
  }], localRoot, '下载');
}
let sftpPath = '.';
let sftpBusy = false;          // 加载锁: 防止双击/连点导致路径重复拼接
// Blob 下载在结束时会同时保留分块和合并后的 Blob。大文件改为直接
// 写入磁盘，避免 Chromium 渲染进程因峰值内存过高而失败。
const LARGE_DOWNLOAD_STREAM_THRESHOLD = 256 * 1024 * 1024;

function fmtSize(n) {
  if (n < 1024) return n + 'B';
  if (n < 1048576) return (n / 1024).toFixed(1) + 'KB';
  if (n < 1073741824) return (n / 1048576).toFixed(1) + 'MB';
  return (n / 1073741824).toFixed(2) + 'GB';
}

function isSftpEligibleTab(tab) {
  return !!(tab && tab.cfg.type === 'ssh' && tab.state === 'connected');
}

function closeSftpPanel() {
  sftpOpen = false;
  sftpConnId = null;
  sftpBusy = false;
  sftpSelectMode = false;
  sftpSelectedItems.clear();
  sftpListEntries = [];
  closeSftpCtxMenu();
  $('sftp-panel')?.classList.add('hidden');
  $('terms')?.classList.remove('sftp-open');
  if ($('sftp-path')) $('sftp-path').value = '';
  if ($('sftp-list')) $('sftp-list').innerHTML = '';
  if ($('sftp-status')) $('sftp-status').textContent = '';
  updateSftpSelectUi();
}

// 文件面板按钮可用性: 仅 SSH 已连接时可用
function updateSftpBtn() {
  const tab = tabs.find(t => t.id === activeTabId);
  const ok = isSftpEligibleTab(tab);
  $('btn-sftp').disabled = !ok;
  $('btn-sftp').title = ok ? 'SSH 文件浏览/下载 (SFTP)' : '文件面板仅 SSH 已连接时可用';
  $('btn-tunnel').disabled = !ok;
  if (ok) $('btn-tunnel').classList.remove('hidden'); else $('btn-tunnel').classList.add('hidden');
  const terminalSession = !!(tab && tab.cfg.type !== 'vnc');
  $('btn-split').disabled = !terminalSession;
  $('btn-cmds').disabled = !terminalSession;
  if (sftpOpen && !ok) closeSftpPanel();
}

function toggleSftpPanel() {
  const tab = tabs.find(t => t.id === activeTabId);
  if (!tab) return setStatus('没有激活的会话');
  if (!isSftpEligibleTab(tab)) return setStatus('文件面板仅支持 SSH 已连接会话');
  if (sftpOpen) {
    closeSftpPanel();
    return;
  }
  sftpOpen = true;
  $('sftp-panel').classList.remove('hidden');
  $('terms').classList.add('sftp-open');
  sftpConnId = tab.id;
  sftpPath = '.';
  sftpBusy = true;
  $('sftp-path').value = '';
  $('sftp-list').innerHTML = '';
  $('sftp-status').textContent = '定位当前目录…';
  // 每次打开都向交互式 shell 查询 pwd，与终端 cwd 同步
  send({ type: 'sftp', id: sftpConnId, action: 'cwd', fresh: true });
  setTimeout(constrainSftpColumns, 0);
}

function sftpLoad() {
  if (sftpBusy || !sftpConnId) return;   // 加载中忽略重复点击
  sftpBusy = true;
  $('sftp-path').value = sftpPath;
  $('sftp-status').textContent = '加载中…';
  send({ type: 'sftp', id: sftpConnId, action: 'list', path: sftpPath });
  // 超时兜底: 8 秒无响应释放锁
  setTimeout(() => { sftpBusy = false; }, 8000);
}

// 绝对路径拼接工具 (服务端返回 realpath 绝对路径)
function sftpJoin(dir, name) {
  return dir.endsWith('/') ? dir + name : `${dir}/${name}`;
}

// ---------- SFTP 远端文件管理 (重命名/删除/权限) ----------
function closeSftpCtxMenu() {
  document.getElementById('sftp-ctx-menu')?.remove();
}

// 通用文件管理请求: 复用 apiUrl 携带 token + window 命名空间
async function sftpFileOp(action, params) {
  if (!sftpConnId) throw new Error('文件面板未连接');
  const resp = await fetch(apiUrl(`/api/sftp/${action}`, { conn: sftpConnId, ...params }), { method: 'POST' });
  const text = await resp.text();
  if (!resp.ok) throw new Error(text || `请求失败: ${resp.status}`);
  let data = {};
  try { data = JSON.parse(text); } catch {}
  return data;
}

async function sftpRenameItem(entry, fullPath) {
  const input = window.prompt(t('sftp_rename_prompt'), entry.name);
  if (input === null) return;
  const newName = input.trim();
  if (!newName || newName === entry.name) return;
  if (newName.includes('/')) return setStatus(t('sftp_rename_invalid'));
  try {
    await sftpFileOp('rename', { path: fullPath, newPath: sftpJoin(sftpPath, newName) });
    setStatus(t('sftp_rename_done') + `: ${newName}`);
    sftpLoad();
  } catch (e) {
    setStatus(`${t('sftp_op_failed')}: ${e.message}`);
  }
}

async function sftpDeleteItem(entry, fullPath) {
  const tip = entry.isDir ? t('sftp_delete_dir_confirm') : t('sftp_delete_confirm');
  if (!window.confirm(`${tip}\n${entry.name}`)) return;
  try {
    const data = await sftpFileOp('delete', { path: fullPath, recursive: entry.isDir ? '1' : '0' });
    setStatus(t('sftp_delete_done') + (data.removed > 1 ? ` (${data.removed})` : ''));
    sftpLoad();
  } catch (e) {
    setStatus(`${t('sftp_op_failed')}: ${e.message}`);
  }
}

async function sftpChmodItem(entry, fullPath) {
  if (entry.isDir) return setStatus(t('sftp_chmod_file_only'));
  const input = window.prompt(t('sftp_chmod_prompt'), '644');
  if (input === null) return;
  const mode = input.trim();
  if (!/^[0-7]{3,4}$/.test(mode)) return setStatus(t('sftp_chmod_invalid'));
  try {
    await sftpFileOp('chmod', { path: fullPath, mode });
    setStatus(`${t('sftp_chmod_done')}: ${mode}`);
    sftpLoad();
  } catch (e) {
    setStatus(`${t('sftp_op_failed')}: ${e.message}`);
  }
}

function showSftpCtxMenu(x, y, entry, fullPath) {
  closeSftpCtxMenu();
  const menu = document.createElement('div');
  menu.id = 'sftp-ctx-menu';
  menu.className = 'sftp-ctx-menu';
  const items = [
    { label: t('sftp_op_rename'), action: () => sftpRenameItem(entry, fullPath) },
    { label: t('sftp_op_delete'), danger: true, action: () => sftpDeleteItem(entry, fullPath) },
    { label: t('sftp_op_chmod'), action: () => sftpChmodItem(entry, fullPath) },
  ];
  for (const item of items) {
    const btn = document.createElement('button');
    btn.className = 'sftp-ctx-item' + (item.danger ? ' danger' : '');
    btn.textContent = item.label;
    btn.addEventListener('click', (ev) => {
      ev.stopPropagation();
      closeSftpCtxMenu();
      item.action();
    });
    menu.appendChild(btn);
  }
  document.body.appendChild(menu);
  // 防止菜单超出窗口右/下边缘
  const rect = menu.getBoundingClientRect();
  menu.style.left = Math.max(4, Math.min(x, window.innerWidth - rect.width - 4)) + 'px';
  menu.style.top = Math.max(4, Math.min(y, window.innerHeight - rect.height - 4)) + 'px';
}

document.addEventListener('click', (e) => {
  const menu = document.getElementById('sftp-ctx-menu');
  if (menu && !menu.contains(e.target)) closeSftpCtxMenu();
});
document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape') closeSftpCtxMenu();
});

function renderSftpList(entries) {
  sftpListEntries = entries;
  const el = $('sftp-list');
  el.innerHTML = '';
  const selHint = sftpSelectMode ? ` · 已选 ${sftpSelectedItems.size}` : '';
  $('sftp-status').textContent = `${entries.length} 项${selHint}`;
  if (!entries.length) {
    el.innerHTML = '<div class="muted" style="padding:12px">(空目录)</div>';
    return;
  }
  for (const e of entries) {
    const full = sftpJoin(sftpPath, e.name);
    const selected = sftpSelectedItems.has(full);
    const row = document.createElement('div');
    row.className = 'sftp-item ' + (e.isDir ? 'dir' : 'file') + (selected ? ' selected' : '');
    row.dataset.full = full;
    const size = e.isDir ? '—' : fmtSize(e.size);
    const time = new Date(e.mtime).toLocaleString('zh-CN',
      { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' });
    row.innerHTML = `
      ${sftpSelectMode ? `<input type="checkbox" class="sftp-select-cb" ${selected ? 'checked' : ''}>` : ''}
      <span class="sftp-ico">${e.isDir ? '📁' : '📄'}</span>
      <span class="sftp-name" title="${esc(e.name)}">${esc(e.name)}</span>
      <span class="sftp-size">${size}</span>
      <span class="sftp-time">${time}</span>
      ${sftpSelectMode ? '' : '<button class="mini sftp-dl" title="' + (e.isDir ? '下载整个目录到本地' : '下载') + '">⬇</button>'}
      ${sftpSelectMode ? '' : `<button class="mini sftp-rename" title="${t('sftp_op_rename')}">✎</button>`}
      ${sftpSelectMode ? '' : `<button class="mini danger sftp-del" title="${t('sftp_op_delete')}">✕</button>`}`;
    row.querySelector('.sftp-select-cb')?.addEventListener('click', (ev) => {
      ev.stopPropagation();
      toggleSftpSelection(full, e);
    });
    row.onclick = () => {
      if (sftpSelectMode) {
        toggleSftpSelection(full, e);
        return;
      }
      if (!e.isDir) return;
      sftpPath = full;
      sftpLoad();
    };
    row.addEventListener('contextmenu', (ev) => {
      ev.preventDefault();
      ev.stopPropagation();
      if (!sftpSelectMode) showSftpCtxMenu(ev.clientX, ev.clientY, e, full);
    });
    row.querySelector('.sftp-dl')?.addEventListener('click', (ev) => {
      ev.stopPropagation();
      downloadSftpItem(e, full);
    });
    row.querySelector('.sftp-rename')?.addEventListener('click', (ev) => {
      ev.stopPropagation();
      sftpRenameItem(e, full);
    });
    row.querySelector('.sftp-del')?.addEventListener('click', (ev) => {
      ev.stopPropagation();
      sftpDeleteItem(e, full);
    });
    el.appendChild(row);
  }
}

// ---------- SFTP 面板宽度调节 ----------
let sftpDragging = false;
let sftpStartX = 0;
let sftpStartWidth = 0;
function initSftpDragger() {
  const divider = $('sftp-divider');
  if (!divider) return;
  divider.addEventListener('mousedown', (e) => {
    e.preventDefault();
    sftpDragging = true;
    sftpStartX = e.clientX;
    const panel = document.getElementById('sftp-panel');
    sftpStartWidth = panel.offsetWidth;
    divider.classList.add('dragging');
    const onMouseMove = (ev) => {
      if (!sftpDragging) return;
      const delta = ev.clientX - sftpStartX;
      const panel = document.getElementById('sftp-panel');
      const workspaceWidth = panel.parentElement ? panel.parentElement.clientWidth : window.innerWidth;
      const maxWidth = Math.max(280, Math.min(1000, workspaceWidth - 160));
      // 面板贴在右侧，左侧分隔条向左拖动时应扩大面板。
      const newWidth = Math.max(280, Math.min(maxWidth, sftpStartWidth - delta));
      panel.style.width = newWidth + 'px';
      $('terms').style.marginRight = '0';
    };
    const onMouseUp = () => {
      sftpDragging = false;
      divider.classList.remove('dragging');
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
    };
    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
  });
}

const SFTP_LOCAL_WIDTH_STORAGE = 'sshterm.sftpLocalWidth';
const SFTP_COLUMN_MIN_WIDTH = 140;

function constrainSftpColumns() {
  const columns = $('sftp-columns');
  const localColumn = $('sftp-local-column');
  const divider = $('sftp-columns-divider');
  const savedWidth = Number(localStorage.getItem(SFTP_LOCAL_WIDTH_STORAGE));
  if (!columns || !localColumn || !divider || !Number.isFinite(savedWidth) || !columns.clientWidth) return;
  const maxWidth = Math.max(SFTP_COLUMN_MIN_WIDTH, columns.clientWidth - divider.offsetWidth - SFTP_COLUMN_MIN_WIDTH);
  localColumn.style.flex = `0 0 ${clamp(savedWidth, SFTP_COLUMN_MIN_WIDTH, maxWidth)}px`;
}
function initSftpColumnsDragger() {
  const columns = $('sftp-columns');
  const localColumn = $('sftp-local-column');
  const remoteColumn = $('sftp-remote-column');
  const divider = $('sftp-columns-divider');
  if (!columns || !localColumn || !remoteColumn || !divider) return;
  constrainSftpColumns();

  divider.addEventListener('mousedown', (e) => {
    e.preventDefault();
    divider.classList.add('dragging');
    const startX = e.clientX;
    const startWidth = localColumn.getBoundingClientRect().width;
    const onMouseMove = (ev) => {
      const maxWidth = Math.max(SFTP_COLUMN_MIN_WIDTH, columns.clientWidth - divider.offsetWidth - SFTP_COLUMN_MIN_WIDTH);
      const width = clamp(startWidth + ev.clientX - startX, SFTP_COLUMN_MIN_WIDTH, maxWidth);
      localColumn.style.flex = `0 0 ${width}px`;
      remoteColumn.style.flex = '1 1 0';
    };
    const onMouseUp = () => {
      divider.classList.remove('dragging');
      localStorage.setItem(SFTP_LOCAL_WIDTH_STORAGE, String(Math.round(localColumn.getBoundingClientRect().width)));
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
    };
    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
  });
}

