// sshterm web module: sftp-xfer — SFTP 上传下载 / 断点续传
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;
// ---------- SFTP 传输 (XHR + 进度条, 大文件不卡页面) ----------
let _progLast = 0;
const transferTasks = [];
let uploadQueuePaused = false;
const UPLOAD_CHUNK_BYTES = 64 * 1024 * 1024;
async function waitForUploadQueue() {
  while (uploadQueuePaused) await new Promise(resolve => setTimeout(resolve, 200));
}
function newTransferTask(kind, name) {
  const task = { id: Date.now() + Math.random(), kind, name, state: 'running', pct: 0, failedFiles: null };
  transferTasks.unshift(task); renderTransferTasks(); return task;
}
function updateTransferTask(task, pct, state, detail = '', failedFiles = null) {
  if (!task) return;
  if (pct !== undefined) task.pct = pct;
  if (state) task.state = state;
  if (detail) task.detail = detail;
  if (failedFiles) task.failedFiles = failedFiles;
  renderTransferTasks();
}

function renderSftpFailures(failedFiles) {
  const box = $('sftp-failures');
  const list = $('sftp-failures-list');
  if (!box || !list) return;
  if (!failedFiles?.length) {
    box.classList.add('hidden');
    list.innerHTML = '';
    return;
  }
  box.classList.remove('hidden');
  list.innerHTML = failedFiles.map((f) =>
    `<div class="sftp-failure-item" title="${esc(f.error)}">`
    + `<span class="sftp-failure-name">${esc(f.name)}</span>`
    + `<span class="sftp-failure-error">${esc(f.error)}</span></div>`,
  ).join('');
}

function formatFailedFileSummary(failedFiles) {
  return failedFiles.map((f) => f.name).join(', ');
}

function renderTransferTasks() {
  const el = $('sftp-tasks'); if (!el) return;
  const list = transferTasks.slice(0, 12); el.classList.toggle('hidden', !list.length);
  el.innerHTML = `<button id="sftp-queue-toggle" class="mini">${uploadQueuePaused ? '▶ 继续队列' : '⏸ 暂停队列'}</button>`
    + list.map((t) => {
      let html = `<div class="sftp-task ${esc(t.state)}"><span>${esc(t.kind)}</span>`
        + `<span class="sftp-task-name">${esc(t.name)}</span>`
        + `<span>${t.state === 'running' ? Math.round(t.pct) + '%' : esc(t.detail || t.state)}</span></div>`;
      if (t.failedFiles?.length) {
        html += t.failedFiles.map((f) =>
          `<div class="sftp-task-failure" title="${esc(f.error)}">`
          + `<span>✕ ${esc(f.name)}</span>`
          + `<span class="sftp-failure-error">${esc(f.error)}</span></div>`,
        ).join('');
      }
      return html;
    }).join('');
  $('sftp-queue-toggle').onclick = () => { uploadQueuePaused = !uploadQueuePaused; renderTransferTasks(); setStatus(uploadQueuePaused ? '上传队列将在当前文件完成后暂停' : '上传队列已继续'); };
}
async function sha256File(file) {
  if (!window.crypto?.subtle || file.size > 256 * 1024 * 1024) return null;
  const digest = await crypto.subtle.digest('SHA-256', await file.arrayBuffer());
  return Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, '0')).join('');
}
function showProgress(text, pct) {
  const now = Date.now();
  if (now - _progLast < 80 && pct !== undefined && pct < 100) return;  // 节流 80ms
  _progLast = now;
  $('sftp-progress').classList.remove('hidden');
  $('sftp-progress-text').textContent = text;
  $('sftp-progress-fill').classList.toggle('indeterminate', pct === undefined);
  if (pct !== undefined) {
    $('sftp-progress-fill').style.width = Math.min(100, Math.round(pct)) + '%';
  }
}
function doneProgress(text) {
  _progLast = 0;
  $('sftp-progress-fill').classList.remove('indeterminate');
  $('sftp-progress-fill').classList.add('done');
  $('sftp-progress-fill').style.width = '100%';
  $('sftp-progress-text').textContent = text;
  setTimeout(() => {
    $('sftp-progress').classList.add('hidden');
    $('sftp-progress-fill').classList.remove('done');
    $('sftp-progress-fill').style.width = '0%';
  }, 2500);
}
// XHR 上传 (带进度) → resolve(status)
function xhrUpload(url, file, onProg, headers) {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('PUT', url);
    if (headers) {
      for (const [k, v] of Object.entries(headers)) xhr.setRequestHeader(k, String(v));
    }
    xhr.upload.onprogress = (e) => {
      if (e.lengthComputable && onProg) onProg(e.loaded, e.total);
    };
    xhr.onload = () => {
      let payload = null;
      try { payload = xhr.responseText ? JSON.parse(xhr.responseText) : null; } catch {}
      resolve({ status: xhr.status, payload });
    };
    xhr.onerror = () => reject(new Error('网络错误'));
    xhr.send(file);
  });
}
let activeDownload = null;
function cancelActiveDownload() {
  if (activeDownload) activeDownload.controller.abort();
}
// 大文件直接写入 File System Access API 提供的临时文件。close() 前由
// 浏览器原子提交；失败/取消时 abort()，不会留下伪装成完整文件的结果。
async function streamDownloadToFile(url, handlePromise, onProg, retries = 3, opts = {}) {
  const handle = await handlePromise;
  const writable = await handle.createWritable();
  const controller = opts.controller || new AbortController();
  const manageActive = opts.manageActive !== false;
  const cancel = $('sftp-cancel-transfer');
  let received = 0;
  let total = 0;
  let remoteIdentity = '';
  let committed = false;
  if (manageActive) {
    activeDownload = { controller };
    cancel.classList.remove('hidden');
    cancel.onclick = cancelActiveDownload;
  }
  try {
    for (let attempt = 0; ; attempt++) {
      try {
        const headers = received > 0
          ? { Range: `bytes=${received}-`, ...(remoteIdentity ? { 'X-Remote-Identity': remoteIdentity } : {}) }
          : {};
        const response = await fetch(url, { headers, signal: controller.signal });
        if (response.status === 412) throw new Error('远端文件已变更，无法续传');
        if (response.status === 416) {
          if (total > 0 && received === total) break;
          throw new Error('续传范围无效');
        }
        if (!response.ok || !response.body) throw new Error(`下载请求失败: ${response.status}`);
        if (received > 0 && response.status !== 206) throw new Error('服务端未接受断点续传');
        remoteIdentity = response.headers.get('X-Remote-Identity') || remoteIdentity;
        const range = response.headers.get('Content-Range');
        const length = Number(response.headers.get('Content-Length') || 0);
        total = range ? Number(range.split('/')[1]) : (length || total);
        if (received > 0) await writable.seek(received);
        const reader = response.body.getReader();
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          await writable.write(value);
          received += value.byteLength;
          if (onProg) onProg(received, total);
        }
        if (total > 0 && received !== total) {
          throw new Error(`下载不完整: ${fmtSize(received)}/${fmtSize(total)}`);
        }
        await writable.close();
        committed = true;
        return { saved: true, size: received, remoteIdentity };
      } catch (error) {
        if (error.name === 'AbortError' || attempt >= retries) throw error;
        setStatus(`下载中断，已从 ${fmtSize(received)} 处自动续传 ${attempt + 1}/${retries}`);
        await new Promise(resolve => setTimeout(resolve, 500 * (attempt + 1)));
      }
    }
  } finally {
    if (!committed) {
      try { await writable.abort(); } catch {}
    }
    if (manageActive) {
      activeDownload = null;
      cancel.classList.add('hidden');
      cancel.onclick = null;
    }
  }
}
// Keep partial data in memory for the current operation and retry a failed
// request from the byte offset already received. This Blob fallback is only
// used below the direct-to-disk threshold.
async function resumableDownload(url, onProg, retries = 3) {
  const chunks = [];
  let received = 0;
  let total = 0;
  let remoteIdentity = '';
  const cancel = $('sftp-cancel-transfer');
  cancel.classList.remove('hidden');
  cancel.onclick = cancelActiveDownload;
  try {
    for (let attempt = 0; ; attempt++) {
      const controller = new AbortController();
      activeDownload = { controller };
      try {
        const headers = received > 0
          ? { Range: `bytes=${received}-`, ...(remoteIdentity ? { 'X-Remote-Identity': remoteIdentity } : {}) }
          : {};
        const response = await fetch(url, { headers, signal: controller.signal });
        if (response.status === 412) throw new Error('远端文件已变更，无法续传');
        if (response.status === 416) {
          if (total > 0 && received === total) {
            return new Blob(chunks, { type: 'application/octet-stream' });
          }
          throw new Error('续传范围无效');
        }
        if (!response.ok || !response.body) throw new Error(`下载请求失败: ${response.status}`);
        if (received > 0 && response.status !== 206) throw new Error('服务端未接受断点续传');
        remoteIdentity = response.headers.get('X-Remote-Identity') || remoteIdentity;
        const range = response.headers.get('Content-Range');
        const length = Number(response.headers.get('Content-Length') || 0);
        total = range ? Number(range.split('/')[1]) : (length || total);
        const reader = response.body.getReader();
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          chunks.push(value);
          received += value.byteLength;
          if (onProg) onProg(received, total);
        }
        if (total > 0 && received !== total) {
          throw new Error(`下载不完整: ${fmtSize(received)}/${fmtSize(total)}`);
        }
        return new Blob(chunks, { type: 'application/octet-stream' });
      } catch (err) {
        if (received && err.name !== 'AbortError') setStatus(`下载中断，已从 ${fmtSize(received)} 处自动续传 ${Math.min(attempt + 1, retries)} 次`);
        if (err.name === 'AbortError' || attempt >= retries) throw err;
        await new Promise(resolve => setTimeout(resolve, 500 * (attempt + 1)));
      } finally {
        activeDownload = null;
      }
    }
  } finally {
    cancel.classList.add('hidden');
    cancel.onclick = null;
  }
}
// Blob 触发浏览器保存
function saveBlob(blob, name) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}

// SFTP 上传: 断点续传 + 大文件分块并行
// 查询远端文件已存在大小 (HEAD)
function remoteSize(url) {
  return new Promise((resolve) => {
    const xhr = new XMLHttpRequest();
    xhr.open('HEAD', url);
    xhr.onload = () => {
      const sz = xhr.getResponseHeader('X-Remote-Size');
      const mt = xhr.getResponseHeader('X-Remote-Mtime');
      resolve({
        size: sz ? parseInt(sz, 10) : 0,
        mtime: mt ? parseInt(mt, 10) : 0,
        status: xhr.status,
      });
    };
    xhr.onerror = () => resolve({ size: 0, mtime: 0, status: 0 });
    xhr.send();
  });
}
async function remoteChecksum(tabId, dirPath, name) {
  const url = apiUrl('/api/sftp/checksum', { conn: tabId, path: `${dirPath}/${name}`.replace(/\/+/g, '/') });
  try {
    const resp = await fetch(url, { cache: 'no-store' });
    if (!resp.ok) return null;
    const data = await resp.json();
    return data.hash || null;
  } catch { return null; }
}
async function uploadFileSmart(tabId, dirPath, name, file, onProg) {
  const base = apiUrl('/api/sftp/upload', { conn: tabId, path: dirPath, name });
  const remote = await remoteSize(base);
  let offset = remote.size > file.size ? 0 : remote.size;
  if (file.size > 0 && offset === file.size) {
    const localHash = await sha256File(file);
    const remoteHash = localHash ? await remoteChecksum(tabId, dirPath, name) : null;
    if (localHash && remoteHash && localHash === remoteHash) {
      onProg(1);
      return { status: 200, payload: { hash: remoteHash }, skipped: true };
    }
    offset = 0;
  }

  // Chunk large uploads: Chrome rejects XHR bodies >= 2GiB
  // (Message size exceeds maximal allowed size).
  const headers = { 'X-Upload-Total-Size': String(file.size) };
  const startOffset = offset;
  let result = { status: 200, payload: null };
  if (file.size === 0) {
    result = await xhrUpload(`${base}&offset=0`, file.slice(0, 0), () => {}, headers);
  } else {
    while (offset < file.size) {
      const end = Math.min(offset + UPLOAD_CHUNK_BYTES, file.size);
      const chunk = file.slice(offset, end);
      const chunkOffset = offset;
      result = await xhrUpload(`${base}&offset=${chunkOffset}`, chunk, (loaded) => {
        onProg((chunkOffset + loaded) / file.size);
      }, headers);
      if (result.status !== 200) {
        result.resumed = startOffset > 0;
        return result;
      }
      offset = end;
    }
  }
  if (file.size > 0) onProg(1);
  result.resumed = startOffset > 0;
  return result;
}
// Non-Chromium fallback: hand the response to the browser download manager,
// which also streams to disk instead of buffering the complete file in JS.
function startNativeDownload(url, name) {
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
}
// 文件上传 (带断点续传/多线程 + 进度条)
$('sftp-upload').onclick = () => $('sftp-file-input').click();
$('sftp-file-input').onchange = async (e) => {
  const files = [...(e.target.files || [])]; if (!files.length) return;
  const snapshot = { connId: sftpConnId, path: sftpPath };
  $('sftp-local-list').innerHTML = files.map(f => `<div class="sftp-item"><span class="sftp-ico">📄</span><span class="sftp-name">${esc(f.name)}</span><span class="sftp-size">${fmtSize(f.size)}</span></div>`).join('');
  for (const file of files) {
    await waitForUploadQueue();
    const task = newTransferTask('上传', file.name); showProgress(`上传: ${file.name} 0%`, 0);
    try {
      const result = await uploadFileSmart(snapshot.connId, snapshot.path, file.name, file,
        p => { showProgress(`上传: ${file.name} ${(p * 100).toFixed(0)}%`, p * 100); updateTransferTask(task, p * 100); });
      if (result.status !== 200) throw new Error('服务端返回 ' + result.status);
      updateTransferTask(task, 100, 'running', '校验中');
      let verified = result.skipped ? '远端已存在完整文件' : (result.resumed ? '续传完成（SSH 完整性已校验）' : 'SSH 完整性已校验');
      if (result.payload?.hash) {
        const localHash = await sha256File(file);
        if (localHash) verified = localHash === result.payload.hash ? 'SHA-256 已校验' : 'SHA-256 不匹配';
      }
      updateTransferTask(task, 100, verified.includes('不匹配') ? 'failed' : 'done', verified);
    } catch (err) { updateTransferTask(task, undefined, 'failed', '失败'); }
  }
  doneProgress(`上传队列完成：${files.length} 项`); sftpLoad();
  e.target.value = '';
};

// SFTP 文件夹上传: XHR 逐个上传 (每个文件进度 + 总计)
$('sftp-upload-dir').onclick = () => $('sftp-dir-input').click();
$('sftp-dir-input').onchange = async (e) => {
  const files = [...(e.target.files || [])];
  if (!files.length) return;
  const snapshot = { connId: sftpConnId, path: sftpPath };
  const total = files.length;
  const totalBytes = files.reduce((sum, file) => sum + file.size, 0);
  const progressByFile = new Array(total).fill(0);
  const rootName = (files[0].webkitRelativePath || files[0].name).split('/')[0];
  const task = newTransferTask('上传目录', rootName);
  let ok = 0, fail = 0;
  let nextFile = 0;
  const updateOverallProgress = (i, filePct, rel) => {
    progressByFile[i] = filePct;
    const transferred = progressByFile.reduce((sum, value, index) => sum + value * files[index].size, 0);
    const pct = totalBytes ? transferred / totalBytes * 100 : progressByFile.filter(value => value >= 1).length / total * 100;
    showProgress(`上传目录: ${rel} ${(filePct * 100).toFixed(0)}%（总计 ${pct.toFixed(0)}%）`, pct);
    updateTransferTask(task, pct);
  };
  const worker = async () => {
    while (nextFile < total) {
      await waitForUploadQueue();
      const i = nextFile++;
      const f = files[i];
      const rel = f.webkitRelativePath || f.name;
      try {
        const result = await uploadFileSmart(snapshot.connId, snapshot.path, rel, f,
          filePct => updateOverallProgress(i, filePct, rel));
        if (result.status === 200) { ok++; updateOverallProgress(i, 1, rel); } else fail++;
      } catch (err) { fail++; }
    }
  };
  // 与服务端的三文件资源上限一致。对大量小文件而言，并行 open/write
  // 可隐藏每个文件的多次网络往返延迟。
  await Promise.all(Array.from({ length: Math.min(3, total) }, worker));
  updateTransferTask(task, 100, fail ? 'failed' : 'done', `${ok}/${total} 成功${fail ? `，${fail} 失败` : ''}`);
  doneProgress(`✅ 文件夹上传完成: ${ok}/${total} 成功${fail ? `, ${fail} 失败` : ''}`);
  sftpLoad();
  e.target.value = '';
};
$('btn-refresh').onclick = () => { send({ type: 'list' }); send({ type: 'serialports' }); };
// 快速连接: 工具栏输入 IP[:端口], 回车直接连接
$('quick-connect').onkeydown = (e) => {
  if (e.key !== 'Enter') return;
  const raw = $('quick-connect').value.trim();
  if (!raw) return;
  const m = raw.match(/^(.+?)(?::(\d+))?$/);
  if (!m) return;
  const host = m[1];
  const port = parseInt(m[2], 10) || 22;
  const type = port === 23 ? 'telnet' : 'ssh';
  newTab({ type, name: `${host}:${port}`, host, port, reconnect: true });
  $('quick-connect').value = '';
  $('quick-connect').blur();
  setStatus(`快速连接: ${host}:${port}`);
};
$('s-refresh').onclick = () => send({ type: 'serialports' });
let serialDtr = false;
let serialRts = false;
function serialControl(action, extra = {}) {
  const tab = tabs.find(t => t.id === activeTabId);
  if (!tab || tab.cfg.type !== 'serial' || tab.state !== 'connected') return setStatus('请先连接串口');
  send({ type: 'serial-control', id: tab.id, action, ...extra });
}
$('s-dtr').onclick = () => { serialDtr = !serialDtr; $('s-dtr').classList.toggle('active', serialDtr); serialControl('signals', { dtr: serialDtr, rts: serialRts }); };
$('s-rts').onclick = () => { serialRts = !serialRts; $('s-rts').classList.toggle('active', serialRts); serialControl('signals', { dtr: serialDtr, rts: serialRts }); };
$('s-break').onclick = () => serialControl('break', { duration: 250 });

// ---------- 拖拽文件上传 (拖文件/文件夹到终端 → SFTP 上传) ----------

// ---- DataTransfer entry / directory drop helpers ----
function collectFileEntriesFromEntry(entry, pathPrefix, out) {
  return new Promise((resolve, reject) => {
    if (!entry) return resolve(out);
    if (entry.isFile) {
      entry.file((file) => {
        const rel = (pathPrefix ? pathPrefix + '/' : '') + file.name;
        try { Object.defineProperty(file, 'webkitRelativePath', { configurable: true, value: rel }); } catch {}
        file._sshtermRelPath = rel;
        out.push(file);
        resolve(out);
      }, reject);
      return;
    }
    if (entry.isDirectory) {
      const reader = entry.createReader();
      const prefix = (pathPrefix ? pathPrefix + '/' : '') + entry.name;
      const readBatch = () => {
        reader.readEntries(async (entries) => {
          if (!entries.length) return resolve(out);
          try {
            for (const child of entries) {
              await collectFileEntriesFromEntry(child, prefix, out);
            }
            readBatch();
          } catch (err) { reject(err); }
        }, reject);
      };
      readBatch();
      return;
    }
    resolve(out);
  });
}

async function collectDataTransferFiles(dataTransfer) {
  const out = [];
  const items = dataTransfer && dataTransfer.items ? [...dataTransfer.items] : [];
  if (items.length && items.some(it => typeof it.webkitGetAsEntry === 'function' && it.webkitGetAsEntry())) {
    for (const item of items) {
      if (item.kind && item.kind !== 'file') continue;
      const entry = item.webkitGetAsEntry ? item.webkitGetAsEntry() : null;
      if (entry) await collectFileEntriesFromEntry(entry, '', out);
    }
    return out;
  }
  return [...((dataTransfer && dataTransfer.files) || [])];
}

async function uploadDroppedFiles(tab, files) {
  if (!files.length) return;
  if (sftpPath === '.') {
    send({ type: 'sftp', id: tab.id, action: 'cwd' });
    await new Promise(r => setTimeout(r, 800));
  }
  const dir = sftpPath || '.';
  const hasRel = files.some(f => f._sshtermRelPath || f.webkitRelativePath);
  if (hasRel && files.length > 1) {
    const total = files.length;
    const totalBytes = files.reduce((sum, file) => sum + file.size, 0);
    const progressByFile = new Array(total).fill(0);
    const rootName = (files[0]._sshtermRelPath || files[0].webkitRelativePath || files[0].name).split('/')[0];
    const task = newTransferTask('上传目录', rootName);
    let ok = 0, fail = 0, nextFile = 0;
    const updateOverallProgress = (i, filePct, rel) => {
      progressByFile[i] = filePct;
      const transferred = progressByFile.reduce((sum, value, index) => sum + value * files[index].size, 0);
      const pct = totalBytes ? transferred / totalBytes * 100 : progressByFile.filter(value => value >= 1).length / total * 100;
      showProgress(`上传目录: ${rel} ${(filePct * 100).toFixed(0)}%（总计 ${pct.toFixed(0)}%）`, pct);
      updateTransferTask(task, pct);
    };
    const worker = async () => {
      while (nextFile < total) {
        await waitForUploadQueue();
        const i = nextFile++;
        const f = files[i];
        const rel = f._sshtermRelPath || f.webkitRelativePath || f.name;
        try {
          const result = await uploadFileSmart(tab.id, dir, rel, f, filePct => updateOverallProgress(i, filePct, rel));
          if (result.status === 200) { ok++; updateOverallProgress(i, 1, rel); } else fail++;
        } catch (err) { fail++; }
      }
    };
    await Promise.all(Array.from({ length: Math.min(3, total) }, worker));
    updateTransferTask(task, 100, fail ? 'failed' : 'done', `${ok}/${total} 成功${fail ? `，${fail} 失败` : ''}`);
    doneProgress(`✅ 文件夹上传完成: ${ok}/${total} 成功${fail ? `, ${fail} 失败` : ''}`);
    if (sftpOpen) sftpLoad();
    return;
  }
  for (const f of files) {
    const name = f._sshtermRelPath || f.webkitRelativePath || f.name;
    setStatus(`上传: ${name} (${fmtSize(f.size)})...`);
    try {
      const result = await uploadFileSmart(tab.id, dir, name, f, progress => {
        showProgress(`上传: ${name} ${(progress * 100).toFixed(0)}%`, progress * 100);
      });
      if (result.status !== 200) throw new Error(`服务端返回 ${result.status}`);
      setStatus(`✅ 已上传: ${name}`);
      doneProgress(`✅ 已上传: ${name}`);
      setTimeout(() => { if (sftpOpen) sftpLoad(); }, 500);
    } catch (err) { setStatus(`上传失败: ${name} — ${err.message}`); }
  }
}


let _dragCounter = 0;
$('terms').addEventListener('dragenter', (e) => {
  if (draggingSessionId) return;
  e.preventDefault();
  _dragCounter++;
  $('terms').classList.add('drag-over');
});
$('terms').addEventListener('dragleave', () => {
  _dragCounter--;
  if (_dragCounter <= 0) { _dragCounter = 0; $('terms').classList.remove('drag-over'); }
});
$('terms').addEventListener('dragover', (e) => {
  if (draggingSessionId) return;
  e.preventDefault();
});
$('terms').addEventListener('drop', async (e) => {
  if (draggingSessionId) return; // 会话列表拖拽排序
  e.preventDefault();
  _dragCounter = 0;
  $('terms').classList.remove('drag-over');
  const tab = tabs.find(t => t.id === activeTabId);
  if (!tab || tab.cfg.type !== 'ssh' || tab.state !== 'connected') return setStatus('拖拽上传仅支持 SSH 已连接时');
  let files = [];
  try {
    files = await collectDataTransferFiles(e.dataTransfer);
  } catch (err) {
    files = [...(e.dataTransfer.files || [])];
  }
  if (!files.length) return;
  await uploadDroppedFiles(tab, files);
});

// SFTP 面板同样支持拖放文件/文件夹上传
(function bindSftpPanelDrop() {
  const panel = $('sftp-panel');
  if (!panel || panel._sshtermDropBound) return;
  panel._sshtermDropBound = true;
  let counter = 0;
  panel.addEventListener('dragenter', (e) => {
    if (draggingSessionId) return;
    e.preventDefault();
    counter++;
    panel.classList.add('drag-over');
  });
  panel.addEventListener('dragleave', () => {
    counter--;
    if (counter <= 0) { counter = 0; panel.classList.remove('drag-over'); }
  });
  panel.addEventListener('dragover', (e) => {
    if (draggingSessionId) return;
    e.preventDefault();
  });
  panel.addEventListener('drop', async (e) => {
    if (draggingSessionId) return;
    e.preventDefault();
    e.stopPropagation();
    counter = 0;
    panel.classList.remove('drag-over');
    const tab = tabs.find(t => t.id === activeTabId);
    if (!tab || tab.cfg.type !== 'ssh' || tab.state !== 'connected') return setStatus('拖拽上传仅支持 SSH 已连接时');
    let files = [];
    try { files = await collectDataTransferFiles(e.dataTransfer); }
    catch (err) { files = [...(e.dataTransfer.files || [])]; }
    if (!files.length) return;
    await uploadDroppedFiles(tab, files);
  });
})();
