// sshterm web module: split-panes — 分屏终端 / 分割条拖拽
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;
// ---------- Split Pane Manager (最多 4 pane, 支持横向/纵向 2x2 + 分割条拖拽) ----------
const SPLIT_STORAGE = 'sshterm.split';
const SPLIT_MAX = 4;
function loadSplitPrefs() {
  try { return JSON.parse(localStorage.getItem(SPLIT_STORAGE) || '{}'); } catch { return {}; }
}
function saveSplitPrefs(prefs) {
  try { localStorage.setItem(SPLIT_STORAGE, JSON.stringify(prefs)); } catch {}
}
function countPanes(tab) { return (tab.extraPanes || []).length + 1; }
function splitDirection(tab) {
  const prefs = loadSplitPrefs();
  return prefs[tab.id] ? prefs[tab.id].dir : 'row';
}
function clampSplitRatio(value) {
  const ratio = Number(value);
  return Number.isFinite(ratio) ? Math.max(0.1, Math.min(0.9, ratio)) : 0.5;
}
function clampGridRatio(value) {
  const ratio = Number(value);
  return Number.isFinite(ratio) ? Math.max(0.2, Math.min(0.8, ratio)) : 0.5;
}
function splitRatio(tab) {
  const prefs = loadSplitPrefs();
  return clampSplitRatio(prefs[tab.id] ? prefs[tab.id].ratio : 0.5);
}
// 2×2 grid layout ratios (col: left column width, row: top row height).
function splitGridRatios(tab) {
  const prefs = loadSplitPrefs();
  const grid = (prefs[tab.id] && prefs[tab.id].grid) || {};
  return { col: clampGridRatio(grid.col), row: clampGridRatio(grid.row) };
}
function findPane(tab, connId) {
  if (tab.id === connId) return tab;
  const p = (tab.extraPanes || []).find(x => x.connId === connId);
  return p || null;
}
function findTabByConnId(connId) {
  for (const t of tabs) {
    if (findPane(t, connId)) return t;
  }
  return null;
}

function createPaneHost(className) {
  const host = document.createElement('div');
  host.className = 'term-host ' + (className || '');
  const closeBtn = document.createElement('button');
  closeBtn.className = 'pane-close';
  closeBtn.textContent = '✕';
  closeBtn.title = '关闭此分屏';
  host.appendChild(closeBtn);
  return host;
}
function createTerminal(host, tabOrPane) {
  const term = new Terminal(getTerminalOptions());
  const fitAddon = new (FitAddonCtor)();
  term.loadAddon(fitAddon);
  const imageAddon = attachImageAddon(term, tabOrPane.cfg?.type);
  term.open(host);
  // Clipboard/key bindings need the concrete terminal object. Split panes
  // previously reached bindClipboard while pane.term was still null, aborting
  // creation before layout and connection setup completed.
  tabOrPane.term = term;
  tabOrPane.fitAddon = fitAddon;
  tabOrPane.imageAddon = imageAddon;
  setTimeout(() => fitAddon.fit(), 0);
  bindClipboard(tabOrPane);
  term.onData((d) => handleUserInput(tabOrPane, d));
  term.onResize(({ cols, rows }) => send({ type: 'resize', id: tabOrPane.connId, cols, rows }));
  return { term, fitAddon, imageAddon };
}

function addPane(tab, dir = 'row', ratio = 0.5, opts = {}) {
  if (countPanes(tab) >= SPLIT_MAX) { setStatus(`最多支持 ${SPLIT_MAX} 个分屏`); return; }
  const restoredId = Number(opts.id);
  const paneId = Number.isInteger(restoredId) && restoredId > 0 && restoredId <= 0xffff
    ? restoredId : tabSeq++;
  tabSeq = Math.max(tabSeq, paneId + 1);
  const host = createPaneHost('pane-split');
  const pane = {
    connId: paneId, term: null, fitAddon: null, imageAddon: null, host,
    cfg: { ...tab.cfg }, state: 'connecting',
    hex: !!tab.hex, recParts: [], recLen: 0, logging: false, logBuf: ''
  };
  tab.extraPanes.push(pane);
  tab.host.appendChild(host);
  const { term, fitAddon, imageAddon } = createTerminal(host, pane);
  pane.term = term;
  pane.fitAddon = fitAddon;
  pane.imageAddon = imageAddon;
  host.querySelector('.pane-close').onclick = () => removePane(tab, pane);
  if (opts.replay) {
    const replay = stripTruncatedSequence(opts.replay);
    pane.recParts = [replay];
    pane.recLen = replay.length;
    try {
      pane.term.write(replay);
      pane.term.write('\r\n\x1b[33m[--- 连接已重新建立 ---]\x1b[0m\r\n');
    } catch {}
  }
  // The browser deliberately holds only a redacted session config after a
  // refresh. Ask the server to clone credentials from the authenticated main
  // connection instead of trying to reconnect with a missing password/key.
  send({ type: 'connect', session: pane.cfg, id: paneId, sourceId: tab.id });
  setStatus('已分屏');
  applySplitLayout(tab, dir, ratio);
  scheduleTabsSave();
  setTimeout(() => { if (tabs.includes(tab)) tab.term.focus(); }, 100);
}

function removePane(tab, pane) {
  send({ type: 'disconnect', id: pane.connId });
  try { pane.term.dispose(); } catch {}
  pane.host.remove();
  const i = tab.extraPanes.indexOf(pane);
  if (i >= 0) tab.extraPanes.splice(i, 1);
  if (tab.extraPanes.length === 0) applySplitLayout(tab, 'none', 1);
  else applySplitLayout(tab, splitDirection(tab), splitRatio(tab));
  scheduleTabsSave();
}

function applyGridRatios(tab) {
  const container = tab.host;
  if (!container) return;
  const { col, row } = splitGridRatios(tab);
  container.style.gridTemplateColumns = `${col}fr ${1 - col}fr`;
  container.style.gridTemplateRows = `${row}fr ${1 - row}fr`;
}

function positionGridDividers(tab) {
  const container = tab.host;
  if (!container || countPanes(tab) < 3 || container.classList.contains('hidden')) return;
  const rect = container.getBoundingClientRect();
  if (!rect.width || !rect.height) return;
  const computed = getComputedStyle(container);
  const boxW = rect.width - parseFloat(computed.paddingLeft) - parseFloat(computed.paddingRight);
  const boxH = rect.height - parseFloat(computed.paddingTop) - parseFloat(computed.paddingBottom);
  if (!(boxW > 0) || !(boxH > 0)) return;
  const { col, row } = splitGridRatios(tab);
  const [v, h] = tab._dividers || [];
  if (v) {
    v.className = 'split-divider grid-divider';
    v.style.display = 'block';
    v.style.left = (col * boxW) + 'px';
    v.style.top = '0';
    v.style.height = boxH + 'px';
  }
  if (h) {
    h.className = 'split-divider grid-divider col';
    h.style.display = 'block';
    h.style.top = (row * boxH) + 'px';
    h.style.left = '0';
    h.style.width = boxW + 'px';
  }
}

function applySplitLayout(tab, dir, ratio) {
  const container = tab.host;
  const main = container.querySelector('.term-host.main-pane');
  if (!container || !main) return;
  ratio = clampSplitRatio(ratio);
  const n = countPanes(tab);
  if (n <= 1 || dir === 'none') {
    (tab._dividers || []).forEach(d => { d.style.display = 'none'; });
    main.style.display = '';
    main.style.flex = '';
    main.style.gridColumn = '';
    main.style.gridRow = '';
    container.style.display = '';
    container.style.flexDirection = '';
    container.style.gridTemplateColumns = '';
    container.style.gridTemplateRows = '';
    return;
  }
  main.style.display = '';
  tab.extraPanes.forEach(p => p.host.classList.remove('hidden'));
  if (n === 2) {
    const divider = tab._dividers?.[0];
    if (divider) {
      divider.className = 'split-divider' + (dir === 'col' ? ' col' : '');
      divider.dataset.dir = dir;
      ['left', 'top', 'width', 'height'].forEach(prop => { divider.style[prop] = ''; });
      divider.style.display = '';
    }
    if (tab._dividers?.[1]) tab._dividers[1].style.display = 'none';
    container.style.display = '';
    container.style.gridTemplateColumns = '';
    container.style.gridTemplateRows = '';
    container.style.flexDirection = dir === 'col' ? 'column' : 'row';
    main.style.flex = `${ratio} 1 0`;
    tab.extraPanes[0].host.style.flex = `${1 - ratio} 1 0`;
  } else if (n >= 3) {
    // 3-4 pane: 2x2 grid with draggable dividers (n===3 leaves the last cell empty).
    container.style.flexDirection = 'column';
    container.style.display = 'grid';
    applyGridRatios(tab);
    [main, ...tab.extraPanes.map(p => p.host)].forEach((hostEl, idx) => {
      hostEl.style.flex = '';
      hostEl.style.gridColumn = (idx % 2) + 1;
      hostEl.style.gridRow = Math.floor(idx / 2) + 1;
    });
    positionGridDividers(tab);
    setTimeout(() => positionGridDividers(tab), 60);
  }
  // save prefs for first pane dir/ratio
  if (!loadSplitPrefs()[tab.id]) saveSplitPrefs({ ...loadSplitPrefs(), [tab.id]: { dir, ratio } });
  setTimeout(() => {
    [tab, ...tab.extraPanes].forEach(x => { try { x.fitAddon.fit(); } catch {} });
  }, 50);
}

function toggleSplit(tab) {
  if (!tab) return;
  const n = countPanes(tab);
  if (n >= SPLIT_MAX) {
    setStatus(`已达分屏上限（${SPLIT_MAX} / 2×2）；请用各分屏 ✕ 关闭后再添加`);
    return;
  }
  // Each click adds one pane up to SPLIT_MAX; individual ✕ closes. Keep 2-pane drag working.
  addPane(tab, splitDirection(tab) || 'row', splitRatio(tab));
}

// replace old split logic with PaneManager
$('btn-split').onclick = () => {
  const tab = tabs.find(t => t.id === activeTabId);
  if (!tab) return setStatus('没有激活的会话');
  if (tab.cfg.type === 'vnc') return setStatus('VNC 会话为独立桌面，不支持终端分屏');
  toggleSplit(tab);
};

function closePane(tab, pane) { removePane(tab, pane); }

function installSplitDragger(tab) {
  const container = tab.host;
  if (!container || container._draggerInstalled) return;
  container._draggerInstalled = true;
  const makeDivider = (dir) => {
    const d = document.createElement('div');
    d.className = 'split-divider ' + (dir === 'col' ? 'col' : '');
    d.style.display = 'none';
    return d;
  };
  tab._dividers = [];
  // NOTE: divider[0] is shared — flex mode (n=2) restyles it via dataset.dir;
  // grid mode (n>=3) treats it as the vertical divider via dataset.gridDir.
  const divider = makeDivider('row');        // n=2: 双向复用；n>=3: 垂直（左右列）分隔条
  const hDivider = makeDivider('col');       // n>=3: 水平（上下行）分隔条
  divider.dataset.gridDir = 'col';           // 网格模式下调整列宽
  hDivider.dataset.gridDir = 'row';          // 网格模式下调整行高
  container.appendChild(divider);
  container.appendChild(hDivider);
  tab._dividers.push(divider, hDivider);
  let dragging = false, dragDir = 'row', dragGridDir = null, dragRatio = null, dragEl = null;
  const fitAll = () => [tab, ...tab.extraPanes].forEach(x => { try { x.fitAddon.fit(); } catch {} });
  const start = (e) => {
    if (e.button != null && e.button !== 0) return;
    dragEl = e.currentTarget;
    dragging = true;
    dragDir = divider.dataset.dir || 'row';
    dragGridDir = countPanes(tab) >= 3 ? (dragEl.dataset.gridDir || null) : null;
    dragRatio = null;
    try { if (e.pointerId != null) dragEl.setPointerCapture(e.pointerId); } catch {}
    e.preventDefault();
  };
  const move = (e) => {
    if (!dragging) return;
    const p = container.getBoundingClientRect();
    if (countPanes(tab) >= 3) {
      // 2×2 grid: adjust gridTemplateColumns / gridTemplateRows ratio (20%-80%).
      if (!dragGridDir) { dragging = false; return; }
      const computed = getComputedStyle(container);
      const boxW = p.width - parseFloat(computed.paddingLeft) - parseFloat(computed.paddingRight);
      const boxH = p.height - parseFloat(computed.paddingTop) - parseFloat(computed.paddingBottom);
      const pos = dragGridDir === 'col' ? e.clientX - (p.left + parseFloat(computed.paddingLeft))
                                        : e.clientY - (p.top + parseFloat(computed.paddingTop));
      const size = dragGridDir === 'col' ? boxW : boxH;
      if (!Number.isFinite(size) || size <= 0) return;
      const ratio = clampGridRatio(pos / size);
      dragRatio = ratio;
      const current = splitGridRatios(tab);
      const next = dragGridDir === 'col' ? { col: ratio, row: current.row } : { col: current.col, row: ratio };
      container.style.gridTemplateColumns = `${next.col}fr ${1 - next.col}fr`;
      container.style.gridTemplateRows = `${next.row}fr ${1 - next.row}fr`;
      positionGridDividers(tab);
      fitAll();
      e.preventDefault();
      return;
    }
    if (tab.extraPanes.length !== 1) { dragging = false; return; }
    const pos = dragDir === 'col' ? e.clientY - p.top : e.clientX - p.left;
    const size = dragDir === 'col' ? p.height : p.width;
    if (!Number.isFinite(size) || size <= 0) return;
    const ratio = clampSplitRatio(pos / size);
    dragRatio = ratio;
    const main = container.querySelector('.term-host.main-pane');
    main.style.flex = `${ratio} 1 0`;
    tab.extraPanes[0].host.style.flex = `${1 - ratio} 1 0`;
    fitAll();
    e.preventDefault();
  };
  const end = (e) => {
    if (!dragging) return;
    dragging = false;
    if (dragGridDir) {
      // Persist the dragged 2×2 grid ratio without clobbering the other axis.
      const prefs = loadSplitPrefs();
      const entry = prefs[tab.id] || {};
      const grid = { col: clampGridRatio(entry.grid?.col), row: clampGridRatio(entry.grid?.row) };
      grid[dragGridDir] = clampGridRatio(Number.isFinite(dragRatio) ? dragRatio : grid[dragGridDir]);
      saveSplitPrefs({ ...prefs, [tab.id]: { ...entry, grid } });
    } else {
      const main = container.querySelector('.term-host.main-pane');
      const mFlex = main.style.flex || '';
      const parsed = parseFloat(mFlex.split(' ')[0]);
      const mRatio = clampSplitRatio(Number.isFinite(dragRatio) ? dragRatio : parsed);
      saveSplitPrefs({ ...loadSplitPrefs(), [tab.id]: { dir: dragDir, ratio: mRatio } });
    }
    dragRatio = null;
    dragGridDir = null;
    saveTabs();
    fitAll();
    try { if (e?.pointerId != null && dragEl) dragEl.releasePointerCapture(e.pointerId); } catch {}
    dragEl = null;
  };
  divider.addEventListener('pointerdown', start);
  hDivider.addEventListener('pointerdown', start);
  document.addEventListener('pointermove', move);
  document.addEventListener('pointerup', end);
  document.addEventListener('pointercancel', end);
  tab._splitCleanup = () => {
    document.removeEventListener('pointermove', move);
    document.removeEventListener('pointerup', end);
    document.removeEventListener('pointercancel', end);
    container._draggerInstalled = false;
  };
}


