// sshterm web module: tunnel-ui — SSH 隧道列表面板
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;

// ---------- SSH 隧道列表渲染 ----------
function renderTunnelList(m) {
  const el = $('tunnel-list');
  const tabs = m.tunnels || [];
  if (tabs.length === 0) {
    el.innerHTML = '<div class="muted" style="padding:12px">暂无隧道</div>';
    return;
  }
  el.innerHTML = tabs.map(t => {
    const typeMap = { local: '本地转发', remote: '远端转发', dynamic: '动态转发(SOCKS5)' };
    const typeLabel = typeMap[t.type] || t.type;
    return `
      <div class="tunnel-item" style="padding:8px; border:1px solid #3a3b4d; margin-bottom:6px; border-radius:4px; background:#1a1b26;">
        <div style="display:flex; justify-content:space-between; align-items:center;">
          <div>
            <strong>${typeLabel}</strong><br>
            <span class="muted">本地:${t.localPort} → ${t.remoteHost}:${t.remotePort}<br>状态:${t.state || 'active'} · 连接:${t.connections || 0} · RX:${t.rxBytes || 0}B · TX:${t.txBytes || 0}B${t.lastError ? `<br>错误:${esc(t.lastError)}` : ''}</span>
          </div>
          <button class="mini danger tunnel-del" data-id="${t.id}" title="删除">🗑</button>
        </div>
      </div>
    `;
  }).join('');
  // 绑定删除按钮事件
  el.querySelectorAll('.tunnel-del').forEach(btn => {
    btn.onclick = (e) => {
      e.stopPropagation();
      const id = parseInt(btn.dataset.id, 10);
      send({ type: 'tunnel', id: tunnelTab.id, action: 'remove', tunnelId: id });
    };
  });
}

// 保存当前激活的 SSH 标签 (隧道面板使用)
var tunnelTab = null;
var tunnelRefreshTimer = null;
function openTunnelPanel(tab) {
  tunnelTab = tab;
  $('dlg-tunnel-mask').classList.remove('hidden');
  send({ type: 'tunnel', id: tab.id, action: 'list' });
  clearInterval(tunnelRefreshTimer);
  tunnelRefreshTimer = setInterval(() => { if (tunnelTab && !$('dlg-tunnel-mask').classList.contains('hidden')) send({ type: 'tunnel', id: tunnelTab.id, action: 'list' }); }, 2000);
}


Sshterm.renderTunnelList = typeof renderTunnelList === 'function' ? renderTunnelList : Sshterm.renderTunnelList;
Sshterm.openTunnelPanel = typeof openTunnelPanel === 'function' ? openTunnelPanel : Sshterm.openTunnelPanel;
