// sshterm web module: vnc-ui — VNC 标签连接 / UI
// Classic script (not type=module). Edit here; web/app.js is generated by scripts/sync-web-app.js.
window.Sshterm = window.Sshterm || {};
var Sshterm = window.Sshterm;
// ---------- VNC 独立会话标签 ----------
let vncModulePromise = null;

function setVncTabStatus(tab, text, state = '') {
  if (!tab?.vncStatus) return;
  tab.vncStatus.textContent = text;
  tab.vncStatus.className = `vnc-session-status${state ? ` ${state}` : ''}`;
}

function setVncTabControls(tab, connected) {
  if (!tab?.vncControls) return;
  tab.vncControls.connect.disabled = connected;
  tab.vncControls.disconnect.disabled = !connected;
  tab.vncControls.cad.disabled = !connected;
  tab.vncControls.fullscreen.disabled = !connected;
}

function initVncSession(tab) {
  tab.vncHost.innerHTML = `
    <div class="vnc-session-toolbar">
      <span class="vnc-session-status">准备连接 ${esc(tab.cfg.host)}:${Number(tab.cfg.port) || 5901}</span>
      <input class="vnc-session-password" type="password" autocomplete="current-password" placeholder="VNC 密码（需要时输入）">
      <label class="vnc-session-check"><input class="vnc-session-view-only" type="checkbox"> 只读</label>
      <button class="vnc-session-connect primary">连接</button>
      <button class="vnc-session-disconnect" disabled>断开</button>
      <button class="vnc-session-cad" disabled>Ctrl+Alt+Del</button>
      <button class="vnc-session-fullscreen" disabled>全屏</button>
    </div>
    <div class="vnc-session-screen"><div class="vnc-placeholder">正在准备独立 VNC 会话…</div></div>`;
  tab.vncStatus = tab.vncHost.querySelector('.vnc-session-status');
  tab.vncScreen = tab.vncHost.querySelector('.vnc-session-screen');
  tab.vncControls = {
    password: tab.vncHost.querySelector('.vnc-session-password'),
    viewOnly: tab.vncHost.querySelector('.vnc-session-view-only'),
    connect: tab.vncHost.querySelector('.vnc-session-connect'),
    disconnect: tab.vncHost.querySelector('.vnc-session-disconnect'),
    cad: tab.vncHost.querySelector('.vnc-session-cad'),
    fullscreen: tab.vncHost.querySelector('.vnc-session-fullscreen'),
  };
  tab.vncControls.viewOnly.checked = !!tab.cfg.viewOnly;
  tab.vncControls.connect.onclick = () => connectVncTab(tab);
  tab.vncControls.disconnect.onclick = () => disconnectVncTab(tab, 'VNC 已断开', true);
  tab.vncControls.cad.onclick = () => { try { tab.rfb?.sendCtrlAltDel(); } catch {} };
  tab.vncControls.fullscreen.onclick = () => tab.vncHost.requestFullscreen?.();
  tab.vncControls.viewOnly.onchange = () => {
    tab.cfg.viewOnly = tab.vncControls.viewOnly.checked;
    if (tab.rfb) tab.rfb.viewOnly = tab.cfg.viewOnly;
    saveTabs();
  };
  tab.vncControls.password.addEventListener('keydown', event => {
    if (event.key === 'Enter') { event.preventDefault(); connectVncTab(tab); }
  });
}

function rememberedVncPassword(tab) {
  if (tab.vncPassword) return Promise.resolve(tab.vncPassword);
  if (!tab.cfg.id || !tab.cfg.rememberPassword || !ws || ws.readyState !== WebSocket.OPEN) return Promise.resolve('');
  const requestId = `vnc-${Date.now()}-${++vncCredentialRequestSeq}`;
  return new Promise(resolve => {
    const timer = setTimeout(() => {
      pendingVncCredentials.delete(requestId);
      resolve('');
    }, 3000);
    pendingVncCredentials.set(requestId, { resolve, timer });
    send({ type: 'vnc-credential', requestId, session: configForBrowserStorage(tab.cfg) });
  });
}

function disconnectVncTab(tab, status = 'VNC 已断开', intentional = false) {
  if (!tab || tab.cfg.type !== 'vnc') return;
  if (intentional) {
    tab.manualDisconnect = true;
    cancelReconnect(tab);
  }
  const current = tab.rfb;
  tab.rfb = null;
  tab.vncCredentialPending = false;
  if (current) { try { current.disconnect(); } catch {} }
  if (tab.vncControls) tab.vncControls.password.value = '';
  setVncTabControls(tab, false);
  setVncTabStatus(tab, status);
  if (tab.vncScreen) tab.vncScreen.innerHTML = '<div class="vnc-placeholder">VNC 已断开。点击“连接”可重新连接此会话。</div>';
  if (tabs.includes(tab)) setTabState(tab.id, 'closed', status);
}

async function connectVncTab(tab) {
  if (!tab || tab.cfg.type !== 'vnc' || !tabs.includes(tab)) return;
  const typedPassword = tab.vncControls?.password.value || '';
  if (tab.rfb && tab.vncCredentialPending) {
    const password = typedPassword || tab.vncPassword;
    if (!password) {
      setVncTabStatus(tab, '请输入 VNC 密码后再次点击“连接”', 'error');
      tab.vncControls.password.focus();
      return;
    }
    tab.vncPassword = password;
    tab.vncCredentialPending = false;
    tab.rfb.sendCredentials({ password });
    tab.vncControls.password.value = '';
    setVncTabStatus(tab, '正在认证…');
    return;
  }
  const host = String(tab.cfg.host || '').trim();
  const port = Number(tab.cfg.port || 5901);
  if (!host || host.length > 253 || !/^[A-Za-z0-9._:-]+$/.test(host) ||
      !Number.isInteger(port) || port < 1 || port > 65535) {
    setTabState(tab.id, 'closed', 'VNC 主机或端口无效');
    setVncTabStatus(tab, 'VNC 主机或端口无效', 'error');
    return;
  }
  tab.manualDisconnect = false;
  cancelReconnect(tab);
  const previous = tab.rfb;
  tab.rfb = null;
  if (previous) { try { previous.disconnect(); } catch {} }
  setTabState(tab.id, 'connecting', `正在连接 ${host}:${port}…`);
  setVncTabControls(tab, false);
  tab.vncControls.connect.disabled = true;
  setVncTabStatus(tab, '正在加载 VNC 客户端…');
  try {
    const password = typedPassword || await rememberedVncPassword(tab);
    if (!tabs.includes(tab) || tab.intentionalClose) return;
    if (password) tab.vncPassword = password;
    vncModulePromise ||= import('/vendor/@novnc/novnc/core/rfb.js');
    const RFB = (await vncModulePromise).default;
    const params = new URLSearchParams({ token: clientToken, host, port: String(port) });
    const protocol = location.protocol === 'https:' ? 'wss:' : 'ws:';
    tab.vncScreen.innerHTML = '';
    const options = { shared: true };
    if (password) options.credentials = { password };
    const instance = new RFB(tab.vncScreen, `${protocol}//${location.host}/vnc?${params}`, options);
    tab.rfb = instance;
    tab.vncCredentialPending = false;
    tab.vncControls.password.value = '';
    instance.scaleViewport = true;
    instance.resizeSession = false;
    instance.viewOnly = !!tab.cfg.viewOnly;
    instance.showDotCursor = true;
    instance.addEventListener('connect', () => {
      if (tab.rfb !== instance) return;
      tab.everConnected = true;
      resetReconnectState(tab);
      setVncTabControls(tab, true);
      setTabState(tab.id, 'connected', `已连接 ${host}:${port}`);
      setVncTabStatus(tab, `已连接：${host}:${port}`, 'ok');
      try { instance.focus(); } catch {}
    });
    instance.addEventListener('credentialsrequired', () => {
      if (tab.rfb !== instance) return;
      tab.vncCredentialPending = true;
      setVncTabControls(tab, false);
      tab.vncControls.connect.disabled = false;
      setVncTabStatus(tab, 'VNC 需要密码：输入后点击“连接”', 'error');
      tab.vncControls.password.focus();
    });
    instance.addEventListener('disconnect', event => {
      if (tab.rfb !== instance) return;
      tab.rfb = null;
      tab.vncCredentialPending = false;
      setVncTabControls(tab, false);
      const clean = !!event.detail?.clean;
      const message = clean ? 'VNC 已断开' : 'VNC 连接异常，请确认远端服务和端口';
      setTabState(tab.id, 'closed', message);
      setVncTabStatus(tab, message, clean ? '' : 'error');
      if (!clean && tab.everConnected && !tab.manualDisconnect) scheduleReconnect(tab, message);
    });
    instance.addEventListener('desktopname', event => {
      if (tab.rfb === instance && event.detail?.name) {
        tab.desktopName = event.detail.name;
        setVncTabStatus(tab, `已连接：${event.detail.name}（${host}:${port}）`, 'ok');
      }
    });
    setVncTabStatus(tab, `正在直接连接 ${host}:${port}…`);
  } catch (error) {
    tab.rfb = null;
    setVncTabControls(tab, false);
    setTabState(tab.id, 'closed', 'VNC 初始化失败');
    setVncTabStatus(tab, `VNC 初始化失败：${error.message || error}`, 'error');
  }
}

